# Generated by Django 5.2.8 on 2025-12-04 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('groups', '0003_groupmembership_rejection_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingresource',
            name='allowed_group',
            field=models.ForeignKey(blank=True, help_text='If set, only members of this group can book this resource.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_resources', to='groups.group'),
        ),
        migrations.AddField(
            model_name='bookingresource',
            name='auto_approve',
            field=models.BooleanField(default=False, help_text='If True, bookings are automatically approved. Otherwise, they require admin approval.'),
        ),
    ]
