# Generated by Django 5.2.8 on 2025-12-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bookingresource_allowed_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingresource',
            name='allowed_user_scope',
            field=models.CharField(choices=[('CLUB', 'Club Members Only'), ('MUNICIPALITY', 'Municipality Members'), ('GLOBAL', 'All App Users'), ('GROUP', 'Specific Group Only')], default='CLUB', max_length=20),
        ),
    ]
