# Generated by Django 5.2.8 on 2025-12-04 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bookingresource_allowed_user_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this is a recurring booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='parent_booking',
            field=models.ForeignKey(blank=True, help_text='The original booking if this is a recurring instance', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurring_end_date',
            field=models.DateTimeField(blank=True, help_text='End date for recurring bookings (calculated automatically)', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurring_type',
            field=models.CharField(blank=True, choices=[('FOREVER', 'Forever'), ('WEEKS', 'For a specific number of weeks')], help_text='Type of recurrence: FOREVER or WEEKS', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurring_weeks',
            field=models.IntegerField(blank=True, help_text='Number of weeks to repeat (only used if recurring_type is WEEKS)', null=True),
        ),
    ]
