# Generated by Django 5.2.8 on 2025-12-04 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_is_recurring_booking_parent_booking_and_more'),
        ('groups', '0003_groupmembership_rejection_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingresource',
            name='qualification_group',
            field=models.ForeignKey(blank=True, help_text='Group that contains qualified members. Only CLOSED groups can be selected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qualification_resources', to='groups.group'),
        ),
        migrations.AlterField(
            model_name='bookingresource',
            name='requires_training',
            field=models.BooleanField(default=False, help_text='If True, user must be a member of the qualification_group to book.'),
        ),
    ]
