# Generated by Django 5.2.8 on 2025-11-23 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country_code', models.CharField(help_text='ISO Code, e.g., SE, NO', max_length=5)),
                ('description', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='countries/avatars/')),
                ('currency_code', models.CharField(blank=True, help_text='e.g., SEK, EUR', max_length=10, null=True)),
                ('default_language', models.CharField(blank=True, help_text='e.g., sv, en', max_length=10, null=True)),
                ('timezone', models.CharField(blank=True, help_text='e.g., Europe/Stockholm', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('terms_and_conditions', models.TextField(help_text='Global terms for this municipality')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='municipalities/avatars/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='municipalities/heroes/')),
                ('municipality_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('allow_self_registration', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='organization.country')),
            ],
            options={
                'verbose_name_plural': 'Municipalities',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('terms_and_conditions', models.TextField()),
                ('club_policies', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='clubs/avatars/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='clubs/heroes/')),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('allowed_age_groups', models.CharField(blank=True, help_text='e.g., 13-19', max_length=100, null=True)),
                ('club_categories', models.CharField(blank=True, help_text='e.g., Gaming, Sports, Art', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='organization.municipality')),
            ],
        ),
    ]
