# Generated by Django 5.2.8 on 2025-11-23 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_club_allowed_age_groups_alter_club_avatar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(help_text="If same as start_date, it's a one-day closure")),
                ('description', models.CharField(help_text='Reason for closure (e.g. Christmas)', max_length=255)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='organization.club')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='DateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('title', models.CharField(blank=True, help_text="e.g., 'Summer Party'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_overrides', to='organization.club')),
            ],
            options={
                'ordering': ['date', 'open_time'],
            },
        ),
        migrations.CreateModel(
            name='RegularOpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('week_cycle', models.CharField(choices=[('ALL', 'Every Week'), ('ODD', 'Odd Weeks (1, 3, 5...)'), ('EVEN', 'Even Weeks (2, 4, 6...)')], default='ALL', max_length=10)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('title', models.CharField(blank=True, help_text="e.g., 'Teen Night'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('allowed_age_groups', models.CharField(blank=True, help_text='Overrides club default if set', max_length=50)),
                ('gender_restriction', models.CharField(choices=[('ALL', 'All Genders'), ('BOYS', 'Boys Only'), ('GIRLS', 'Girls Only'), ('OTHER', 'Other')], default='ALL', max_length=10)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regular_hours', to='organization.club')),
            ],
            options={
                'ordering': ['weekday', 'open_time'],
            },
        ),
    ]
