# Generated by Django 5.2.8 on 2025-11-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_clubclosure_dateoverride_regularopeninghour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, help_text="Emoji or Icon name (e.g. '⚽' or 'sports_soccer')", max_length=50)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
