# Generated by Django 5.2.8 on 2025-11-23 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='interests/avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'webp'])]),
        ),
    ]
