# Generated by Django 5.2.8 on 2025-11-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_interest_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regularopeninghour',
            name='allowed_age_groups',
        ),
        migrations.AddField(
            model_name='regularopeninghour',
            name='max_value',
            field=models.IntegerField(blank=True, help_text='Max Age or Grade', null=True),
        ),
        migrations.AddField(
            model_name='regularopeninghour',
            name='min_value',
            field=models.IntegerField(blank=True, help_text='Min Age or Grade', null=True),
        ),
        migrations.AddField(
            model_name='regularopeninghour',
            name='restriction_mode',
            field=models.CharField(choices=[('NONE', 'No Restriction'), ('AGE', 'Age Range'), ('GRADE', 'Grade Range')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='regularopeninghour',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
