# Generated by Django 5.2.8 on 2025-11-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_remove_regularopeninghour_allowed_age_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='allow_self_registration_override',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='require_guardian_override',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='require_guardian_at_registration',
            field=models.BooleanField(default=False),
        ),
    ]
