# Generated by Django 5.2.8 on 2025-12-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_club_allow_self_registration_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='borrowing_requires_checkin',
            field=models.BooleanField(default=False, help_text='If True, user must be checked in to borrow items.'),
        ),
        migrations.AddField(
            model_name='club',
            name='max_active_loans_per_user',
            field=models.IntegerField(default=3, help_text='Maximum number of items a user can borrow simultaneously.'),
        ),
    ]
