# Generated by Django 5.2.8 on 2025-12-25 05:08

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    """Populate slug fields for existing municipalities and clubs"""
    Municipality = apps.get_model('organization', 'Municipality')
    Club = apps.get_model('organization', 'Club')
    
    # Populate municipality slugs
    for muni in Municipality.objects.all():
        base_slug = slugify(muni.name)
        slug = base_slug
        counter = 1
        while Municipality.objects.filter(slug=slug).exclude(pk=muni.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        muni.slug = slug
        muni.save()
    
    # Populate club slugs
    for club in Club.objects.all():
        base_slug = slugify(club.name)
        slug = base_slug
        counter = 1
        while Club.objects.filter(slug=slug).exclude(pk=club.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        club.slug = slug
        club.save()


def reverse_slugs(apps, schema_editor):
    """Reverse migration - clear slugs"""
    Municipality = apps.get_model('organization', 'Municipality')
    Club = apps.get_model('organization', 'Club')
    
    Municipality.objects.all().update(slug='')
    Club.objects.all().update(slug='')


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_club_borrowing_requires_checkin_and_more'),
    ]

    operations = [
        # Step 1: Add slug fields WITHOUT unique constraint
        migrations.AddField(
            model_name='municipality',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text="URL-friendly identifier (e.g. 'kramfors')"),
        ),
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.SlugField(blank=True, default='', help_text="URL-friendly identifier (e.g. 'kramfors-fritidsgard')"),
        ),
        
        # Step 2: Populate slugs for existing records
        migrations.RunPython(populate_slugs, reverse_slugs),
        
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name='municipality',
            name='slug',
            field=models.SlugField(blank=True, help_text="URL-friendly identifier (e.g. 'kramfors')", unique=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='slug',
            field=models.SlugField(blank=True, help_text="URL-friendly identifier (e.g. 'kramfors-fritidsgard')", unique=True),
        ),
    ]
