# Generated by Django 5.2.8 on 2025-12-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_club_slug_municipality_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='data_retention_months',
            field=models.PositiveIntegerField(blank=True, help_text='Override: Months of inactivity before user data deletion. Null = use global default', null=True),
        ),
    ]
