# Generated by Django 5.2.8 on 2026-01-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_municipality_data_retention_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='trial_period_days_override',
            field=models.PositiveIntegerField(blank=True, help_text='Override municipality trial period. Null = use municipality setting, 0 = disabled', null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='trial_period_days',
            field=models.PositiveIntegerField(default=0, help_text='Days new youth members can access platform before verification. 0 = disabled (require verification immediately)'),
        ),
    ]
