# Generated by Django 5.2.8 on 2026-01-12 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', help_text='Current status of the export', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the export was requested')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the request', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When processing started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When processing completed', null=True)),
                ('file_path', models.CharField(blank=True, help_text='Path to the export file (S3 or local)', max_length=500)),
                ('file_size', models.BigIntegerField(blank=True, help_text='Size of export file in bytes', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the download link expires (7 days)', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if export failed')),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('task_id', models.CharField(blank=True, help_text='Celery task ID for tracking', max_length=255)),
                ('user', models.ForeignKey(help_text='User who requested the export', on_delete=django.db.models.deletion.CASCADE, related_name='data_export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Export Request',
                'verbose_name_plural': 'Data Export Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DataExportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(help_text="Section of data (e.g., 'profile', 'posts', 'messages')", max_length=100)),
                ('record_count', models.IntegerField(default=0, help_text='Number of records exported in this section')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('SKIPPED', 'Skipped'), ('ERROR', 'Error')], default='SUCCESS', help_text='Status of this section export', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if section failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('export_request', models.ForeignKey(help_text='Associated export request', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gdpr.dataexportrequest')),
            ],
            options={
                'verbose_name': 'Data Export Log Entry',
                'verbose_name_plural': 'Data Export Log Entries',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dataexportrequest',
            index=models.Index(fields=['user', '-requested_at'], name='gdpr_export_user_time_idx'),
        ),
        migrations.AddIndex(
            model_name='dataexportrequest',
            index=models.Index(fields=['status', '-requested_at'], name='gdpr_export_status_time_idx'),
        ),
    ]
