# Generated by Django 5.2.8 on 2026-01-12 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text="Unique code for this consent type (e.g., 'terms_of_service')", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name of this consent type', max_length=200)),
                ('description', models.TextField(help_text='Description of what the user is consenting to')),
                ('version', models.CharField(help_text="Version of the consent (e.g., '1.0', '2023-01-15')", max_length=20)),
                ('is_required', models.BooleanField(default=False, help_text='Whether this consent is required for registration')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this consent is currently active')),
                ('legal_basis', models.CharField(blank=True, help_text='Legal basis for this consent (GDPR Article)', max_length=100)),
                ('consent_text', models.TextField(help_text='The actual text the user consents to')),
                ('document_url', models.URLField(blank=True, help_text='URL to full document (e.g., Privacy Policy)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display consents')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this consent type', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_types_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consent Type',
                'verbose_name_plural': 'Consent Types',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consented_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When consent was given')),
                ('consent_method', models.CharField(choices=[('REGISTRATION', 'During registration'), ('SETTINGS', 'In settings page'), ('PROMPT', 'Via consent prompt'), ('API', 'Via API'), ('ADMIN', 'By administrator')], default='REGISTRATION', help_text='How consent was obtained', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when consent was given', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device user agent')),
                ('consent_text_snapshot', models.TextField(help_text='Snapshot of consent text at time of consent')),
                ('version_snapshot', models.CharField(help_text='Version of consent at time of consent', max_length=20)),
                ('withdrawn_at', models.DateTimeField(blank=True, db_index=True, help_text='When consent was withdrawn (if applicable)', null=True)),
                ('withdrawal_reason', models.TextField(blank=True, help_text='Reason for withdrawal (optional)')),
                ('withdrawal_ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when consent was withdrawn', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether consent is currently active')),
                ('consent_type', models.ForeignKey(help_text='Type of consent given', on_delete=django.db.models.deletion.PROTECT, related_name='user_consents', to='gdpr.consenttype')),
                ('user', models.ForeignKey(help_text='User who gave consent', on_delete=django.db.models.deletion.CASCADE, related_name='consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Consent',
                'verbose_name_plural': 'User Consents',
                'ordering': ['-consented_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('GIVEN', 'Consent given'), ('WITHDRAWN', 'Consent withdrawn'), ('UPDATED', 'Consent updated'), ('VIEWED', 'Consent document viewed'), ('REMINDED', 'Consent reminder sent')], help_text='Type of event', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the event occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the event', null=True)),
                ('details', models.JSONField(blank=True, help_text='Additional event details', null=True)),
                ('user_consent', models.ForeignKey(help_text='Related user consent', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gdpr.userconsent')),
            ],
            options={
                'verbose_name': 'Consent Log Entry',
                'verbose_name_plural': 'Consent Log Entries',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='userconsent',
            index=models.Index(fields=['user', 'consent_type'], name='gdpr_consent_user_type_idx'),
        ),
        migrations.AddIndex(
            model_name='userconsent',
            index=models.Index(fields=['user', 'is_active'], name='gdpr_consent_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='userconsent',
            index=models.Index(fields=['consent_type', 'is_active'], name='gdpr_consent_type_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='userconsent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user', 'consent_type'), name='unique_active_consent'),
        ),
    ]
