# Generated by Django 5.2.8 on 2026-01-12 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0002_consenttype_userconsent_consentlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When deletion was requested')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='pending', help_text='Current status of the deletion request', max_length=20)),
                ('deletion_type', models.CharField(choices=[('full', 'Full Deletion'), ('anonymize', 'Anonymize')], default='anonymize', help_text='Type of deletion to perform', max_length=20)),
                ('reason', models.TextField(blank=True, help_text="User's reason for deletion (optional)")),
                ('grace_period_days', models.IntegerField(default=30, help_text='Days until permanent deletion (grace period)')),
                ('scheduled_deletion_date', models.DateTimeField(db_index=True, help_text='When the account will be permanently deleted')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the deletion was processed', null=True)),
                ('processing_time_seconds', models.IntegerField(blank=True, help_text='Time taken to process deletion', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, help_text='When the deletion was cancelled', null=True)),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when request was made', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/device user agent')),
                ('error_message', models.TextField(blank=True, help_text='Error details if deletion failed')),
                ('data_exported', models.BooleanField(default=False, help_text='Whether user exported their data before deletion')),
                ('reminder_sent_at', models.DateTimeField(blank=True, help_text='When reminder email was sent', null=True)),
                ('final_warning_sent_at', models.DateTimeField(blank=True, help_text='When final warning email was sent', null=True)),
                ('user', models.OneToOneField(help_text='User who requested account deletion', on_delete=django.db.models.deletion.CASCADE, related_name='deletion_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Deletion Request',
                'verbose_name_plural': 'Account Deletion Requests',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='DeletedUserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_user_id', models.IntegerField(db_index=True, help_text='Original user ID (for foreign key integrity)', unique=True)),
                ('email_hash', models.CharField(db_index=True, help_text='SHA-256 hash of email (to prevent re-registration)', max_length=64)),
                ('deletion_date', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the user was deleted')),
                ('deletion_reason', models.TextField(blank=True, help_text='Reason for deletion')),
                ('deletion_type', models.CharField(choices=[('full', 'Full Deletion'), ('anonymize', 'Anonymize')], help_text='Type of deletion performed', max_length=20)),
                ('registration_date', models.DateTimeField(blank=True, help_text='When user originally registered', null=True)),
                ('last_login_date', models.DateTimeField(blank=True, help_text="User's last login before deletion", null=True)),
                ('retention_until', models.DateTimeField(db_index=True, help_text='When this record can be permanently removed')),
            ],
            options={
                'verbose_name': 'Deleted User Record',
                'verbose_name_plural': 'Deleted User Records',
                'ordering': ['-deletion_date'],
                'indexes': [models.Index(fields=['retention_until'], name='gdpr_deleted_retention_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this log entry was created')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('success', 'Success')], default='info', help_text='Log level', max_length=20)),
                ('action', models.CharField(help_text="Action performed (e.g., 'Deleted user posts')", max_length=100)),
                ('model_name', models.CharField(blank=True, help_text='Name of model affected', max_length=100)),
                ('count', models.IntegerField(blank=True, help_text='Number of records affected', null=True)),
                ('details', models.JSONField(blank=True, help_text='Additional details in JSON format', null=True)),
                ('deletion_request', models.ForeignKey(help_text='Related deletion request', on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='gdpr.accountdeletionrequest')),
            ],
            options={
                'verbose_name': 'Deletion Log Entry',
                'verbose_name_plural': 'Deletion Log Entries',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='accountdeletionrequest',
            index=models.Index(fields=['status', 'scheduled_deletion_date'], name='gdpr_del_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='accountdeletionrequest',
            index=models.Index(fields=['scheduled_deletion_date'], name='gdpr_del_sched_date_idx'),
        ),
    ]
