# Generated by Django 5.2.8 on 2026-01-13 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr', '0003_accountdeletionrequest_deleteduserrecord_deletionlog_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('sv', 'Swedish'), ('en', 'English'), ('ar', 'Arabic'), ('da', 'Danish'), ('fi', 'Finnish'), ('nb', 'Norwegian'), ('prs', 'Dari/Persian'), ('so', 'Somali')], help_text='Language code for this translation', max_length=10)),
                ('name', models.CharField(help_text='Translated display name', max_length=200)),
                ('description', models.TextField(help_text='Translated description')),
                ('consent_text', models.TextField(help_text='Translated consent text (the full legal text)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='gdpr.consenttype')),
            ],
            options={
                'verbose_name': 'Consent Type Translation',
                'verbose_name_plural': 'Consent Type Translations',
                'ordering': ['consent_type', 'language'],
                'unique_together': {('consent_type', 'language')},
            },
        ),
        migrations.CreateModel(
            name='ConsentTypeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='Version identifier', max_length=20)),
                ('consent_text_snapshot', models.TextField(help_text='Snapshot of consent text at this version')),
                ('translations_snapshot', models.JSONField(default=dict, help_text='Snapshot of all translations at this version')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('change_summary', models.TextField(blank=True, help_text='Summary of changes in this version')),
                ('consent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='gdpr.consenttype')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this version', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consent Type Version',
                'verbose_name_plural': 'Consent Type Versions',
                'ordering': ['-created_at'],
                'unique_together': {('consent_type', 'version')},
            },
        ),
    ]
