# Generated by Django 5.2.8 on 2025-12-25 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Ungdomsappen - Hitta aktiviteter nära dig', max_length=255)),
                ('meta_description', models.TextField(help_text='Global meta description for the start page')),
                ('keywords', models.CharField(help_text='Comma separated keywords', max_length=500)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
            options={
                'verbose_name': 'Startpage SEO Settings',
                'verbose_name_plural': 'Startpage SEO Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(default='Ungdom', help_text='e.g. Youth Member, Parent', max_length=100)),
                ('quote', models.TextField()),
                ('rating', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
