# Generated by Django 5.2.8 on 2025-12-25 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='siteseosettings',
            name='hero_background',
            field=models.FileField(blank=True, help_text='High res background image (recommended: 1920x1080px)', null=True, upload_to='marketing/hero/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='siteseosettings',
            name='hero_cta_text',
            field=models.CharField(default='Sök aktiviteter', help_text='Text on the main search button', max_length=50),
        ),
        migrations.AddField(
            model_name='siteseosettings',
            name='hero_subtitle',
            field=models.CharField(default='Samlade aktiviteter och evenemang för unga.', help_text='Subtext under headline', max_length=255),
        ),
        migrations.AddField(
            model_name='siteseosettings',
            name='hero_title',
            field=models.CharField(default='Hitta din grej!', help_text='Main headline on start page', max_length=100),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_avatar',
            field=models.FileField(blank=True, help_text='Optional avatar image for the author', null=True, upload_to='marketing/testimonials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AlterField(
            model_name='siteseosettings',
            name='keywords',
            field=models.CharField(default='ungdomsappen, fritidsgård, aktiviteter, ungdom, evenemang', help_text='Comma separated keywords', max_length=500),
        ),
        migrations.AlterField(
            model_name='siteseosettings',
            name='meta_description',
            field=models.TextField(default='Upptäck aktiviteter, evenemang och fritidsgårdar nära dig. Ungdomsappen samlar allt för unga på ett ställe.', help_text='Global meta description for the start page'),
        ),
    ]
