# Generated by Django 5.2.8 on 2025-12-25 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_alter_testimonial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer/Partner name', max_length=100)),
                ('logo', models.FileField(help_text='Customer logo (recommended: PNG with transparent background)', upload_to='marketing/customers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('website_url', models.URLField(blank=True, help_text="Link to customer's website (optional)", null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show on homepage')),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
