# Generated by Django 5.2.8 on 2026-01-01 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteseosettings',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Background video for hero section (recommended: MP4, max 30MB, 1920x1080px)', null=True, upload_to='marketing/hero/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])]),
        ),
        migrations.AlterField(
            model_name='siteseosettings',
            name='hero_background',
            field=models.FileField(blank=True, help_text='Fallback background image if no video (recommended: 1920x1080px)', null=True, upload_to='marketing/hero/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
