# Generated by Django 5.2.8 on 2026-01-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_add_hero_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(blank=True, choices=[('sv', 'Svenska'), ('en', 'English'), ('da', 'Dansk'), ('nb', 'Norsk'), ('fi', 'Suomi'), ('ar', 'العربية'), ('so', 'Soomaali'), ('prs', 'دری')], db_index=True, help_text='Language for this customer (leave empty to show for all languages)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='siteseosettings',
            name='language',
            field=models.CharField(choices=[('sv', 'Svenska'), ('en', 'English'), ('da', 'Dansk'), ('nb', 'Norsk'), ('fi', 'Suomi'), ('ar', 'العربية'), ('so', 'Soomaali'), ('prs', 'دری')], db_index=True, default='sv', help_text='Language for this content', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='language',
            field=models.CharField(choices=[('sv', 'Svenska'), ('en', 'English'), ('da', 'Dansk'), ('nb', 'Norsk'), ('fi', 'Suomi'), ('ar', 'العربية'), ('so', 'Soomaali'), ('prs', 'دری')], db_index=True, default='sv', help_text='Language for this testimonial', max_length=10),
        ),
    ]
