# Generated by Django 5.2.8 on 2025-12-05 17:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_groupmembership_rejection_count'),
        ('organization', '0008_club_borrowing_requires_checkin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Rich text description of the event')),
                ('cover_image', models.FileField(blank=True, null=True, upload_to='events/covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('video_url', models.URLField(blank=True, help_text='Optional YouTube/Vimeo embed link', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty for free events', max_digits=10, null=True)),
                ('organizer_name', models.CharField(blank=True, help_text='Override name if different from Club', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('recurrence_pattern', models.CharField(choices=[('NONE', 'Does not repeat'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', max_length=20)),
                ('next_occurrence', models.DateTimeField(blank=True, null=True)),
                ('location_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_map_visible', models.BooleanField(default=True, help_text='Show map on event page')),
                ('is_global', models.BooleanField(default=False, help_text='Visible to everyone in the system (Super Admin)')),
                ('target_audience', models.CharField(choices=[('YOUTH', 'Youth Only'), ('GUARDIAN', 'Guardians Only'), ('BOTH', 'Both Youth and Guardians')], default='YOUTH', max_length=20)),
                ('target_genders', models.JSONField(blank=True, default=list, help_text='List of genders e.g. ["MALE", "FEMALE"]')),
                ('target_min_age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_max_age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100)])),
                ('target_grades', models.JSONField(blank=True, default=list, help_text='List of grades e.g. [7, 8, 9]')),
                ('allow_registration', models.BooleanField(default=True)),
                ('requires_verified_account', models.BooleanField(default=False)),
                ('requires_guardian_approval', models.BooleanField(default=False)),
                ('requires_admin_approval', models.BooleanField(default=False)),
                ('registration_open_date', models.DateTimeField(blank=True, null=True)),
                ('registration_close_date', models.DateTimeField(blank=True, null=True)),
                ('max_seats', models.PositiveIntegerField(default=0, help_text='0 = Unlimited')),
                ('max_waitlist', models.PositiveIntegerField(default=0, help_text='0 = No waitlist')),
                ('enable_tickets', models.BooleanField(default=True, help_text='Generate QR code tickets upon confirmed seat')),
                ('send_reminders', models.BooleanField(default=True, help_text='Send automated 24h and 2h reminders')),
                ('custom_welcome_message', models.TextField(blank=True, help_text='Message sent in notification when seat is confirmed')),
                ('confirmed_participants_count', models.PositiveIntegerField(default=0)),
                ('waitlist_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organization.club')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='organization.municipality')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='targeted_events', to='groups.group')),
                ('target_interests', models.ManyToManyField(blank=True, related_name='targeted_events', to='organization.interest')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='EventDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='events/docs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt'])])),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='events.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='events/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='events.event')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING_GUARDIAN', 'Waiting for Guardian'), ('PENDING_ADMIN', 'Waiting for Admin'), ('APPROVED', 'Confirmed Seat'), ('WAITLIST', 'On Waitlist'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled by User'), ('ATTENDED', 'Checked In')], default='APPROVED', max_length=20)),
                ('approval_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_event_registrations', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EventTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_code', models.CharField(editable=False, max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_tickets', to=settings.AUTH_USER_MODEL)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='events.eventregistration')),
            ],
        ),
    ]
