# Generated by Django 5.2.8 on 2025-12-05 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='parent_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_instances', to='events.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_end_date',
            field=models.DateField(blank=True, help_text='Last date of the recurring series', null=True),
        ),
    ]
