# Generated by Django 5.2.8 on 2025-12-06 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_parent_event_event_recurrence_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta description for search engines', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='meta_tags',
            field=models.CharField(blank=True, help_text='Comma-separated meta tags/keywords', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='og_description',
            field=models.TextField(blank=True, help_text='Open Graph description for social media sharing', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='og_image',
            field=models.FileField(blank=True, help_text='Open Graph image for social media sharing', null=True, upload_to='events/og-images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='event',
            name='og_title',
            field=models.CharField(blank=True, help_text='Open Graph title for social media sharing', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='page_title',
            field=models.CharField(blank=True, help_text='Custom page title (defaults to event title if not set)', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the title (auto-generated if not provided)', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='event',
            name='twitter_card_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary_large_image', help_text='Twitter card type', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='twitter_description',
            field=models.TextField(blank=True, help_text='Twitter card description', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='twitter_image',
            field=models.FileField(blank=True, help_text='Twitter card image', null=True, upload_to='events/twitter-images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='event',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter card title', max_length=255),
        ),
    ]
