# Generated by Django 5.2.8 on 2025-12-06 08:44

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Event = apps.get_model('events', 'Event')
    for event in Event.objects.filter(slug__isnull=True):
        base_slug = slugify(event.title)
        slug = base_slug
        counter = 1
        # Ensure uniqueness
        while Event.objects.filter(slug=slug).exclude(pk=event.pk).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1
        event.slug = slug
        event.save(update_fields=['slug'])


def reverse_populate_slugs(apps, schema_editor):
    # No need to reverse - we can leave slugs as they are
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_add_seo_fields'),
    ]

    operations = [
        migrations.RunPython(populate_slugs, reverse_populate_slugs),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of the title (auto-generated if not provided)', max_length=255, unique=True),
        ),
    ]
