# Generated by Django 5.2.8 on 2025-12-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_make_slug_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='scheduled_publish_date',
            field=models.DateTimeField(blank=True, help_text='Optional: Schedule when to publish this event. If set and status is SCHEDULED, status will change to PUBLISHED automatically at this time.', null=True),
        ),
    ]
