# Generated by Django 5.2.8 on 2026-01-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_fix_target_max_age_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_mode',
            field=models.CharField(choices=[('OPEN', 'Open (No registration required)'), ('FIRST_COME', 'First Come First Served'), ('MANUAL_APPROVAL', 'Manual Approval Only')], default='FIRST_COME', help_text='How spots are assigned: OPEN (no registration), FIRST_COME (automatic), MANUAL_APPROVAL (admin picks)', max_length=20),
        ),
    ]
