# Generated by Django 5.2.8 on 2026-01-04 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('event_registration_confirmed', 'Event Registration Confirmed'), ('event_waitlist_added', 'Added to Event Waitlist'), ('event_guardian_approval_needed', 'Guardian Approval Needed (Event)'), ('booking_confirmed', 'Booking Confirmed'), ('booking_pending', 'Booking Pending Approval'), ('booking_approved', 'Booking Approved'), ('booking_declined', 'Booking Declined'), ('booking_cancelled', 'Booking Cancelled'), ('group_application_approved', 'Group Application Approved'), ('group_application_rejected', 'Group Application Rejected'), ('group_joined', 'Joined Group'), ('reward_earned', 'Reward Earned'), ('system_message', 'System Message'), ('news_published', 'News Published'), ('questionnaire_available', 'Questionnaire Available'), ('survey_reminder', 'Survey Reminder'), ('inventory_overdue', 'Inventory Overdue'), ('inventory_available', 'Inventory Available')], help_text='The type of notification this template is for', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable name for this template', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of when this notification is sent')),
                ('available_variables', models.JSONField(default=list, help_text='List of available template variables with descriptions')),
                ('category', models.CharField(choices=[('SYSTEM', 'System Message'), ('REWARD', 'Reward'), ('EVENT', 'Event'), ('NEWS', 'News'), ('POST', 'Post'), ('BOOKING', 'Booking'), ('GROUP', 'Group'), ('INVENTORY', 'Inventory'), ('QUESTIONNAIRE', 'Questionnaire')], default='SYSTEM', help_text='Default category for notifications using this template', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='If disabled, notifications of this type will not be sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('SYSTEM', 'System Message'), ('REWARD', 'Reward'), ('EVENT', 'Event'), ('NEWS', 'News'), ('POST', 'Post'), ('BOOKING', 'Booking'), ('GROUP', 'Group'), ('INVENTORY', 'Inventory'), ('QUESTIONNAIRE', 'Questionnaire')], max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationTemplateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('sv', 'Swedish'), ('en', 'English'), ('ar', 'Arabic'), ('da', 'Danish'), ('fi', 'Finnish'), ('nb', 'Norwegian'), ('prs', 'Dari/Persian'), ('so', 'Somali')], help_text='Language code for this translation', max_length=10)),
                ('title', models.CharField(help_text='Notification title (can include variables like {{event_title}})', max_length=255)),
                ('body', models.TextField(help_text='Notification body text (can include variables like {{event_title}})')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='notifications.notificationtemplate')),
            ],
            options={
                'verbose_name': 'Notification Template Translation',
                'verbose_name_plural': 'Notification Template Translations',
                'ordering': ['template', 'language'],
                'unique_together': {('template', 'language')},
            },
        ),
    ]
