# Generated by Django

from django.db import migrations


def create_default_templates(apps, schema_editor):
    """Create default notification templates with Swedish and English translations."""
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    NotificationTemplateTranslation = apps.get_model('notifications', 'NotificationTemplateTranslation')

    # Define templates with their translations
    templates = [
        # ===== EVENTS =====
        {
            'type': 'event_registration_confirmed',
            'name': 'Event Registration Confirmed',
            'description': 'Sent when a user successfully registers for an event',
            'category': 'EVENT',
            'available_variables': [
                {'name': 'event_title', 'description': 'Title of the event'},
            ],
            'translations': {
                'sv': {
                    'title': 'Anmälan bekräftad! ✅',
                    'body': 'Du är nu anmäld till {{event_title}}. Vi ses där!',
                },
                'en': {
                    'title': 'Registration Confirmed! ✅',
                    'body': 'You are now registered for {{event_title}}. See you there!',
                },
            },
        },
        {
            'type': 'event_waitlist_added',
            'name': 'Added to Event Waitlist',
            'description': 'Sent when a user is added to the waitlist for a full event',
            'category': 'EVENT',
            'available_variables': [
                {'name': 'event_title', 'description': 'Title of the event'},
            ],
            'translations': {
                'sv': {
                    'title': 'Tillagd på väntelista',
                    'body': 'Eventet är fullt, men du står på väntelistan för {{event_title}}. Vi meddelar dig om en plats blir ledig.',
                },
                'en': {
                    'title': 'Added to Waitlist',
                    'body': 'The event is full, but you are on the waitlist for {{event_title}}. We\'ll notify you if a spot opens up.',
                },
            },
        },
        {
            'type': 'event_guardian_approval_needed',
            'name': 'Guardian Approval Needed (Event)',
            'description': 'Sent when event registration requires guardian approval',
            'category': 'EVENT',
            'available_variables': [
                {'name': 'event_title', 'description': 'Title of the event'},
            ],
            'translations': {
                'sv': {
                    'title': 'Vårdnadshavare måste godkänna',
                    'body': 'Din anmälan till {{event_title}} väntar på godkännande från din vårdnadshavare.',
                },
                'en': {
                    'title': 'Guardian Approval Needed',
                    'body': 'Your registration for {{event_title}} is waiting for your guardian\'s approval.',
                },
            },
        },
        
        # ===== BOOKINGS =====
        {
            'type': 'booking_confirmed',
            'name': 'Booking Confirmed',
            'description': 'Sent when a booking is auto-approved or admin-created',
            'category': 'BOOKING',
            'available_variables': [
                {'name': 'resource_name', 'description': 'Name of the booked resource'},
                {'name': 'date', 'description': 'Date of the booking'},
                {'name': 'time', 'description': 'Time of the booking'},
            ],
            'translations': {
                'sv': {
                    'title': 'Bokning bekräftad! ✅',
                    'body': 'Din bokning av {{resource_name}} den {{date}} kl {{time}} är bekräftad.',
                },
                'en': {
                    'title': 'Booking Confirmed! ✅',
                    'body': 'Your booking for {{resource_name}} on {{date}} at {{time}} is confirmed.',
                },
            },
        },
        {
            'type': 'booking_pending',
            'name': 'Booking Pending Approval',
            'description': 'Sent when a booking requires staff approval',
            'category': 'BOOKING',
            'available_variables': [
                {'name': 'resource_name', 'description': 'Name of the booked resource'},
            ],
            'translations': {
                'sv': {
                    'title': 'Bokningsförfrågan mottagen ⏳',
                    'body': 'Vi har tagit emot din förfrågan om {{resource_name}}. Du får besked när personalen har granskat den.',
                },
                'en': {
                    'title': 'Booking Request Received ⏳',
                    'body': 'We received your request for {{resource_name}}. You will be notified once staff reviews it.',
                },
            },
        },
        {
            'type': 'booking_approved',
            'name': 'Booking Approved',
            'description': 'Sent when a pending booking is approved by staff',
            'category': 'BOOKING',
            'available_variables': [
                {'name': 'resource_name', 'description': 'Name of the booked resource'},
                {'name': 'date', 'description': 'Date of the booking'},
                {'name': 'time', 'description': 'Time of the booking'},
            ],
            'translations': {
                'sv': {
                    'title': 'Bokning godkänd! 🎉',
                    'body': 'Goda nyheter! Din bokning av {{resource_name}} den {{date}} kl {{time}} har godkänts.',
                },
                'en': {
                    'title': 'Booking Approved! 🎉',
                    'body': 'Great news! Your booking for {{resource_name}} on {{date}} at {{time}} has been approved.',
                },
            },
        },
        {
            'type': 'booking_declined',
            'name': 'Booking Declined',
            'description': 'Sent when a booking is declined by staff',
            'category': 'BOOKING',
            'available_variables': [
                {'name': 'resource_name', 'description': 'Name of the booked resource'},
                {'name': 'reason', 'description': 'Reason for declining (optional)'},
            ],
            'translations': {
                'sv': {
                    'title': 'Bokning nekad ❌',
                    'body': 'Tyvärr kunde din bokning av {{resource_name}} inte godkännas. {{reason}}',
                },
                'en': {
                    'title': 'Booking Declined ❌',
                    'body': 'Unfortunately, your booking for {{resource_name}} could not be approved. {{reason}}',
                },
            },
        },
        {
            'type': 'booking_cancelled',
            'name': 'Booking Cancelled',
            'description': 'Sent when a booking is cancelled',
            'category': 'BOOKING',
            'available_variables': [
                {'name': 'resource_name', 'description': 'Name of the booked resource'},
                {'name': 'reason', 'description': 'Reason for cancellation (optional)'},
            ],
            'translations': {
                'sv': {
                    'title': 'Bokning avbokad ⚠️',
                    'body': 'Din bokning av {{resource_name}} har avbokats. {{reason}}',
                },
                'en': {
                    'title': 'Booking Cancelled ⚠️',
                    'body': 'Your booking for {{resource_name}} has been cancelled. {{reason}}',
                },
            },
        },
        
        # ===== GROUPS =====
        {
            'type': 'group_application_approved',
            'name': 'Group Application Approved',
            'description': 'Sent when a group membership application is approved',
            'category': 'GROUP',
            'available_variables': [
                {'name': 'group_name', 'description': 'Name of the group'},
            ],
            'translations': {
                'sv': {
                    'title': 'Välkommen till gruppen! 🎉',
                    'body': 'Din ansökan till {{group_name}} har godkänts. Du är nu medlem!',
                },
                'en': {
                    'title': 'Welcome to the group! 🎉',
                    'body': 'Your application to {{group_name}} has been approved. You are now a member!',
                },
            },
        },
        {
            'type': 'group_application_rejected',
            'name': 'Group Application Rejected',
            'description': 'Sent when a group membership application is rejected',
            'category': 'GROUP',
            'available_variables': [
                {'name': 'group_name', 'description': 'Name of the group'},
            ],
            'translations': {
                'sv': {
                    'title': 'Ansökan nekad',
                    'body': 'Din ansökan till {{group_name}} har tyvärr nekats.',
                },
                'en': {
                    'title': 'Application Rejected',
                    'body': 'Your application to {{group_name}} has been rejected.',
                },
            },
        },
        {
            'type': 'group_joined',
            'name': 'Joined Group',
            'description': 'Sent when a user joins an open/closed group',
            'category': 'GROUP',
            'available_variables': [
                {'name': 'group_name', 'description': 'Name of the group'},
            ],
            'translations': {
                'sv': {
                    'title': 'Du har gått med i en grupp!',
                    'body': 'Du är nu medlem i {{group_name}}.',
                },
                'en': {
                    'title': 'You joined a group!',
                    'body': 'You are now a member of {{group_name}}.',
                },
            },
        },
        
        # ===== REWARDS =====
        {
            'type': 'reward_earned',
            'name': 'Reward Earned',
            'description': 'Sent when a user earns a reward',
            'category': 'REWARD',
            'available_variables': [
                {'name': 'reward_name', 'description': 'Name of the reward'},
            ],
            'translations': {
                'sv': {
                    'title': '🎁 Ny belöning upplåst!',
                    'body': 'Grattis! Du har fått: {{reward_name}}',
                },
                'en': {
                    'title': '🎁 New Reward Unlocked!',
                    'body': 'Congratulations! You have received: {{reward_name}}',
                },
            },
        },
        
        # ===== NEWS & SYSTEM =====
        {
            'type': 'system_message',
            'name': 'System Message',
            'description': 'Sent for system-wide announcements',
            'category': 'SYSTEM',
            'available_variables': [
                {'name': 'message_title', 'description': 'Title of the system message'},
                {'name': 'message_preview', 'description': 'Preview of the message content'},
            ],
            'translations': {
                'sv': {
                    'title': 'Meddelande: {{message_title}}',
                    'body': '{{message_preview}}',
                },
                'en': {
                    'title': 'Message: {{message_title}}',
                    'body': '{{message_preview}}',
                },
            },
        },
        {
            'type': 'news_published',
            'name': 'News Published',
            'description': 'Sent when a news article is published',
            'category': 'NEWS',
            'available_variables': [
                {'name': 'news_title', 'description': 'Title of the news article'},
                {'name': 'news_excerpt', 'description': 'Short excerpt from the article'},
            ],
            'translations': {
                'sv': {
                    'title': 'Nyhet: {{news_title}}',
                    'body': '{{news_excerpt}}',
                },
                'en': {
                    'title': 'News: {{news_title}}',
                    'body': '{{news_excerpt}}',
                },
            },
        },
        
        # ===== QUESTIONNAIRES =====
        {
            'type': 'questionnaire_available',
            'name': 'Questionnaire Available',
            'description': 'Sent when a new questionnaire is available for the user',
            'category': 'QUESTIONNAIRE',
            'available_variables': [
                {'name': 'questionnaire_title', 'description': 'Title of the questionnaire'},
            ],
            'translations': {
                'sv': {
                    'title': '📋 Ny enkät tillgänglig',
                    'body': 'En ny enkät väntar på dig: {{questionnaire_title}}',
                },
                'en': {
                    'title': '📋 New Questionnaire Available',
                    'body': 'A new questionnaire is waiting for you: {{questionnaire_title}}',
                },
            },
        },
        {
            'type': 'survey_reminder',
            'name': 'Survey Reminder',
            'description': 'Reminder to complete an unfinished survey',
            'category': 'QUESTIONNAIRE',
            'available_variables': [
                {'name': 'questionnaire_title', 'description': 'Title of the questionnaire'},
            ],
            'translations': {
                'sv': {
                    'title': 'Slutför din enkät!',
                    'body': 'Du började på "{{questionnaire_title}}" men har inte slutfört den än. Slutför den nu för att eventuellt få belöningar!',
                },
                'en': {
                    'title': 'Finish your survey!',
                    'body': 'You started "{{questionnaire_title}}" but haven\'t finished it yet. Complete it now to potentially earn rewards!',
                },
            },
        },
        
        # ===== INVENTORY =====
        {
            'type': 'inventory_overdue',
            'name': 'Inventory Overdue',
            'description': 'Sent when a borrowed item is overdue',
            'category': 'INVENTORY',
            'available_variables': [
                {'name': 'item_name', 'description': 'Name of the borrowed item'},
                {'name': 'overdue_time', 'description': 'How long the item has been overdue'},
            ],
            'translations': {
                'sv': {
                    'title': '⚠️ Försenad återlämning',
                    'body': '{{item_name}} skulle ha lämnats tillbaka. Den är nu {{overdue_time}} försenad.',
                },
                'en': {
                    'title': '⚠️ Overdue Return',
                    'body': '{{item_name}} was due to be returned. It is now {{overdue_time}} overdue.',
                },
            },
        },
        {
            'type': 'inventory_available',
            'name': 'Inventory Available',
            'description': 'Sent when an item becomes available from the queue',
            'category': 'INVENTORY',
            'available_variables': [
                {'name': 'item_name', 'description': 'Name of the item'},
            ],
            'translations': {
                'sv': {
                    'title': '✅ Artikel tillgänglig!',
                    'body': '{{item_name}} som du stod i kö för är nu tillgänglig!',
                },
                'en': {
                    'title': '✅ Item Available!',
                    'body': '{{item_name}} that you were queued for is now available!',
                },
            },
        },
    ]

    # Create templates and their translations
    for template_data in templates:
        template = NotificationTemplate.objects.create(
            type=template_data['type'],
            name=template_data['name'],
            description=template_data['description'],
            category=template_data['category'],
            available_variables=template_data['available_variables'],
            is_active=True,
        )
        
        for lang_code, translation_data in template_data['translations'].items():
            NotificationTemplateTranslation.objects.create(
                template=template,
                language=lang_code,
                title=translation_data['title'],
                body=translation_data['body'],
            )


def delete_default_templates(apps, schema_editor):
    """Remove default templates."""
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    NotificationTemplate.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_add_notification_templates'),
    ]

    operations = [
        migrations.RunPython(create_default_templates, delete_default_templates),
    ]

