# Generated by Django

from django.db import migrations


def add_questionnaire_reward_template(apps, schema_editor):
    """Add the questionnaire reward earned notification template."""
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    NotificationTemplateTranslation = apps.get_model('notifications', 'NotificationTemplateTranslation')

    # Create the template
    template = NotificationTemplate.objects.create(
        type='questionnaire_reward_earned',
        name='Questionnaire Reward Earned',
        description='Sent when a user completes a questionnaire and earns a reward',
        category='REWARD',
        available_variables=[
            {'name': 'reward_name', 'description': 'Name of the reward earned'},
            {'name': 'questionnaire_title', 'description': 'Title of the completed questionnaire'},
        ],
        is_active=True,
    )
    
    # Add Swedish translation
    NotificationTemplateTranslation.objects.create(
        template=template,
        language='sv',
        title='🎁 Ny belöning upplåst!',
        body='Du har fått en ny belöning: {{reward_name}}. Kolla din plånbok för att använda den!',
    )
    
    # Add English translation
    NotificationTemplateTranslation.objects.create(
        template=template,
        language='en',
        title='🎁 New Reward Unlocked!',
        body='You earned a new reward: {{reward_name}}. Check your wallet to claim it!',
    )


def remove_questionnaire_reward_template(apps, schema_editor):
    """Remove the questionnaire reward earned notification template."""
    NotificationTemplate = apps.get_model('notifications', 'NotificationTemplate')
    NotificationTemplate.objects.filter(type='questionnaire_reward_earned').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_add_default_notification_templates'),
    ]

    operations = [
        migrations.RunPython(add_questionnaire_reward_template, remove_questionnaire_reward_template),
    ]

