# Generated by Django 5.2.8 on 2026-01-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_questionnaire_reward_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('SYSTEM', 'System Message'), ('REWARD', 'Reward'), ('EVENT', 'Event'), ('NEWS', 'News'), ('POST', 'Post'), ('BOOKING', 'Booking'), ('GROUP', 'Group'), ('INVENTORY', 'Inventory'), ('QUESTIONNAIRE', 'Questionnaire'), ('MESSAGE', 'Message')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='category',
            field=models.CharField(choices=[('SYSTEM', 'System Message'), ('REWARD', 'Reward'), ('EVENT', 'Event'), ('NEWS', 'News'), ('POST', 'Post'), ('BOOKING', 'Booking'), ('GROUP', 'Group'), ('INVENTORY', 'Inventory'), ('QUESTIONNAIRE', 'Questionnaire'), ('MESSAGE', 'Message')], default='SYSTEM', help_text='Default category for notifications using this template', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(choices=[('event_registration_confirmed', 'Event Registration Confirmed'), ('event_waitlist_added', 'Added to Event Waitlist'), ('event_guardian_approval_needed', 'Guardian Approval Needed (Event)'), ('booking_confirmed', 'Booking Confirmed'), ('booking_pending', 'Booking Pending Approval'), ('booking_approved', 'Booking Approved'), ('booking_declined', 'Booking Declined'), ('booking_cancelled', 'Booking Cancelled'), ('group_application_approved', 'Group Application Approved'), ('group_application_rejected', 'Group Application Rejected'), ('group_joined', 'Joined Group'), ('reward_earned', 'Reward Earned'), ('system_message', 'System Message'), ('news_published', 'News Published'), ('questionnaire_available', 'Questionnaire Available'), ('survey_reminder', 'Survey Reminder'), ('questionnaire_reward_earned', 'Questionnaire Reward Earned'), ('inventory_overdue', 'Inventory Overdue'), ('inventory_available', 'Inventory Available'), ('message_received', 'New Message Received'), ('message_reaction', 'Message Reaction')], help_text='The type of notification this template is for', max_length=50, unique=True),
        ),
    ]
