# Generated by Django 5.2.8 on 2025-12-01 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0007_club_allow_self_registration_override_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('method', models.CharField(choices=[('QR_KIOSK', 'QR Kiosk Scan'), ('MANUAL_ADMIN', 'Manual Admin Entry'), ('MANUAL_SELF', 'Manual Self Check-in')], default='QR_KIOSK', max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='organization.club')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_checkins', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-check_in_at'],
                'indexes': [models.Index(fields=['club', 'check_in_at'], name='visits_chec_club_id_dc634e_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('total_visits', models.IntegerField(default=0)),
                ('total_minutes', models.IntegerField(default=0)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'club', 'year', 'month')},
            },
        ),
    ]
