# Generated by Django 5.2.8 on 2026-01-12 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinsession',
            name='method',
            field=models.CharField(choices=[('QR_KIOSK', 'QR Kiosk Scan'), ('PIN_CODE', 'PIN Code Entry'), ('MANUAL_ADMIN', 'Manual Admin Entry'), ('MANUAL_SELF', 'Manual Self Check-in')], default='QR_KIOSK', max_length=20),
        ),
    ]
