# Generated by Django 5.2.8 on 2025-11-27 18:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0006_remove_regularopeninghour_allowed_age_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='groups/avatars/')),
                ('group_type', models.CharField(choices=[('OPEN', 'Open (Join Freely)'), ('APPLICATION', 'Application Required'), ('CLOSED', 'Closed (Invite Only)')], default='OPEN', max_length=20)),
                ('target_member_type', models.CharField(choices=[('YOUTH', 'Youth Only'), ('GUARDIAN', 'Guardians Only')], default='YOUTH', max_length=20)),
                ('is_system_group', models.BooleanField(default=False)),
                ('system_group_type', models.CharField(choices=[('NONE', 'Standard Group'), ('REGISTERED', 'All Registered'), ('ACTIVE', 'Active Members'), ('VERIFIED', 'Verified Members')], default='NONE', max_length=20)),
                ('min_age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grades', models.JSONField(blank=True, default=list, help_text='List of allowed grades')),
                ('genders', models.JSONField(blank=True, default=list, help_text='List of allowed genders')),
                ('custom_field_rules', models.JSONField(blank=True, default=dict, help_text='Rules based on custom field values')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='organization.club')),
                ('interests', models.ManyToManyField(blank=True, related_name='targeted_groups', to='organization.interest')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='organization.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved (Active)'), ('REJECTED', 'Rejected')], default='APPROVED', max_length=20)),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN', 'Group Admin')], default='MEMBER', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
    ]
