# Generated by Django 5.2.8 on 2025-11-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='background_image',
            field=models.FileField(blank=True, null=True, upload_to='groups/backgrounds/'),
        ),
    ]
