# Generated by Django 5.2.8 on 2025-12-03 17:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0003_groupmembership_rejection_count'),
        ('organization', '0008_club_borrowing_requires_checkin_and_more'),
        ('rewards', '0003_alter_rewardusage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('admin_level', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MUNICIPALITY_ADMIN', 'Municipality Admin'), ('CLUB_ADMIN', 'Club Admin')], max_length=50)),
                ('target_audience', models.CharField(choices=[('YOUTH', 'Youth Members'), ('GUARDIAN', 'Guardians'), ('BOTH', 'Both (via Groups)')], default='YOUTH', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False, help_text='If True, admins cannot see who gave which answer.')),
                ('start_date', models.DateTimeField(help_text='When the survey becomes available.')),
                ('expiration_date', models.DateTimeField(help_text='When the survey closes.')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('benefit_limit', models.IntegerField(blank=True, help_text='Max number of users who can claim the reward (e.g. First 10).', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='organization.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_questionnaires', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='organization.municipality')),
                ('rewards', models.ManyToManyField(blank=True, help_text='Rewards granted upon completion.', related_name='questionnaires', to='rewards.reward')),
                ('visibility_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questionnaires', to='groups.group')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('description', models.TextField(blank=True, help_text='Optional helper text for the user.')),
                ('image', models.FileField(blank=True, null=True, upload_to='questions/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('question_type', models.CharField(choices=[('FREE_TEXT', 'Free Text'), ('RATING', 'Star Rating (1-5)'), ('SINGLE_CHOICE', 'Single Choice'), ('MULTI_CHOICE', 'Multiple Choice')], default='FREE_TEXT', max_length=20)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('parent_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_questions', to='questionnaires.question')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaires.questionnaire')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('COMPLETED', 'Completed')], default='STARTED', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_benefit_claimed', models.BooleanField(default=False, help_text='True if the user successfully claimed the attached reward.')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questionnaires.questionnaire')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'questionnaire')},
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, help_text='Value stored in DB for analytics', max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='questionnaires.question')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='trigger_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_questions', to='questionnaires.questionoption'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('rating_answer', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaires.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaires.questionnaireresponse')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='selected_in_answers', to='questionnaires.questionoption')),
            ],
        ),
    ]
