# Generated by Django 5.2.8 on 2025-12-03 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireresponse',
            name='last_reminded_at',
            field=models.DateTimeField(blank=True, help_text='When the last reminder notification was sent.', null=True),
        ),
    ]
