# Generated by Django 5.2.8 on 2025-12-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_questionnaireresponse_last_reminded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='scheduled_publish_date',
            field=models.DateTimeField(blank=True, help_text='Optional: Schedule when to publish this questionnaire. If set, status will change to PUBLISHED automatically at this time.', null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='When the survey becomes available. Auto-set to now when published.', null=True),
        ),
    ]
