# Generated by Django 5.2.8 on 2025-12-26 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0009_club_slug_municipality_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="Key used in code check (e.g., 'inventory')", unique=True)),
                ('description', models.TextField(blank=True)),
                ('monthly_price_sek', models.DecimalField(decimal_places=2, default=0, help_text='Price if purchased as a standalone add-on', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_extra_club_sek', models.DecimalField(decimal_places=2, default=500.0, max_digits=10)),
                ('analytics_package_price_sek', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Global Pricing',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('monthly_price_sek', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_public', models.BooleanField(default=True, help_text='Visible in the upgrade menu')),
                ('is_active', models.BooleanField(default=True, help_text='If False, no new licenses can use this plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('features', models.ManyToManyField(blank=True, related_name='plans', to='licensing.feature')),
            ],
        ),
        migrations.CreateModel(
            name='LicenseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('NEW_CLUB', 'Buy Extra Club Slot'), ('UPGRADE_PLAN', 'Upgrade Plan Tier'), ('ADD_FEATURE', 'Buy Add-on Feature'), ('ADD_ANALYTICS', 'Buy Analytics Package'), ('RENEWAL', 'License Renewal')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved & Invoiced'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('requested_club_count', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for Super Admin (e.g. Invoice ID)')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='license_requests', to='organization.municipality')),
                ('requested_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licensing.feature')),
                ('requested_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licensing.plan')),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_clubs', models.PositiveIntegerField(default=3, help_text='Total number of clubs allowed')),
                ('has_analytics', models.BooleanField(default=False, help_text='Has purchased the Analytics Suite')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('auto_renew', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_features', models.ManyToManyField(blank=True, related_name='extra_licenses', to='licensing.feature')),
                ('municipality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='license', to='organization.municipality')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='licenses', to='licensing.plan')),
            ],
        ),
    ]
