# Generated by Django 5.2.8 on 2025-12-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpricing',
            name='yearly_renewal_discount_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Discount percentage for yearly renewals (e.g., 10 = 10% off)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='globalpricing',
            name='analytics_package_price_sek',
            field=models.DecimalField(decimal_places=2, default=1000.0, help_text='Monthly price for analytics package', max_digits=10),
        ),
        migrations.AlterField(
            model_name='globalpricing',
            name='price_per_extra_club_sek',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Monthly price per extra club slot', max_digits=10),
        ),
    ]
