# Generated by Django 5.2.8 on 2025-12-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0002_globalpricing_yearly_renewal_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenserequest',
            name='renewal_years',
            field=models.PositiveIntegerField(blank=True, help_text='Number of years for renewal request', null=True),
        ),
    ]
