# Generated by Django 5.2.8 on 2025-12-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing', '0003_licenserequest_renewal_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalDataRetentionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_retention_months', models.PositiveIntegerField(default=12, help_text='Default months of inactivity before user data is deleted')),
                ('min_allowed_retention_months', models.PositiveIntegerField(default=6, help_text='Minimum retention period municipalities can set')),
                ('max_allowed_retention_months', models.PositiveIntegerField(default=36, help_text='Maximum retention period municipalities can set')),
                ('warning_notification_days', models.PositiveIntegerField(default=30, help_text='Days before deletion to send warning notification to user')),
                ('second_warning_notification_days', models.PositiveIntegerField(default=7, help_text='Days before deletion to send final warning notification')),
                ('is_auto_deletion_enabled', models.BooleanField(default=False, help_text='If False, system only logs who would be deleted (dry run mode)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Global Data Retention Settings',
                'verbose_name_plural': 'Global Data Retention Settings',
            },
        ),
    ]
