// frontend/app/admin/super/seo/links/page.tsx
'use client';

import { useState, useEffect, useRef, Suspense } from 'react';
import Link from 'next/link';
import { useRouter, usePathname, useSearchParams } from 'next/navigation';
import { 
  Link2, Plus, Trash2, Search, X, Loader2, ArrowLeft,
  ExternalLink, Wand2, ChevronLeft, ChevronRight
} from 'lucide-react';
import { seoApi } from '@/lib/seo-api';
import { InternalLink } from '@/types/seo';
import { useToast } from '@/hooks/useToast';
import ConfirmationModal from '@/app/components/ConfirmationModal';

function Skeleton({ className }: { className?: string }) {
  return (
    <div 
      className={`animate-pulse bg-[var(--dark-600)] rounded ${className}`}
      style={{
        backgroundImage: 'linear-gradient(90deg, transparent, rgba(255,255,255,0.05), transparent)',
        backgroundSize: '200% 100%',
        animation: 'shimmer 1.5s infinite, pulse 2s infinite'
      }}
    />
  );
}

function InternalLinksContent() {
  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();
  
  const [links, setLinks] = useState<InternalLink[]>([]);
  const [totalCount, setTotalCount] = useState(0);
  const [loading, setLoading] = useState(true);
  const [searchInput, setSearchInput] = useState(searchParams.get('search') || '');
  const [filterAutoGenerated, setFilterAutoGenerated] = useState<string>(searchParams.get('filter') || '');
  const [linkToDelete, setLinkToDelete] = useState<InternalLink | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [saving, setSaving] = useState(false);
  const [generating, setGenerating] = useState(false);
  const { success, error } = useToast();
  const searchInputRef = useRef<HTMLInputElement>(null);
  
  const pageSize = 10;
  const currentPage = Number(searchParams.get('page')) || 1;
  const totalPages = Math.ceil(totalCount / pageSize);
  
  const [form, setForm] = useState({
    source_url: '',
    target_url: '',
    anchor_text: '',
    link_strength: '5',
  });

  // Update URL helper
  const updateUrl = (key: string, value: string) => {
    const params = new URLSearchParams(searchParams.toString());
    if (value) params.set(key, value); else params.delete(key);
    // Reset page to 1 when filters change (except when changing page itself)
    if (key !== 'page') {
      params.set('page', '1');
    }
    router.push(`${pathname}?${params.toString()}`);
  };

  const handlePageChange = (newPage: number) => {
    updateUrl('page', newPage.toString());
  };

  const fetchLinks = async () => {
    setLoading(true);
    try {
      const params: any = { 
        page: currentPage,
        page_size: pageSize 
      };
      
      const filter = searchParams.get('filter') || '';
      if (filter !== '') params.is_auto_generated = filter === 'true';
      
      const search = searchParams.get('search') || '';
      if (search) params.search = search;
      
      const data = await seoApi.getInternalLinks(params);
      setLinks(data.results || []);
      setTotalCount(data.count || 0);
    } catch (err) {
      console.error('Failed to fetch links:', err);
      error('Kunde inte ladda länkar');
    } finally {
      setLoading(false);
    }
  };

  // Debounced search update
  useEffect(() => {
    const timer = setTimeout(() => {
      const currentSearch = searchParams.get('search') || '';
      if (searchInput !== currentSearch) {
        updateUrl('search', searchInput);
      }
    }, 500);
    return () => clearTimeout(timer);
  }, [searchInput]);

  // Sync searchInput with URL when it changes externally
  useEffect(() => {
    const urlSearch = searchParams.get('search') || '';
    if (urlSearch !== searchInput && document.activeElement !== searchInputRef.current) {
      setSearchInput(urlSearch);
    }
  }, [searchParams]);

  // Sync filter with URL
  useEffect(() => {
    const urlFilter = searchParams.get('filter') || '';
    if (urlFilter !== filterAutoGenerated) {
      setFilterAutoGenerated(urlFilter);
    }
  }, [searchParams]);

  // Fetch links when URL params change
  useEffect(() => {
    fetchLinks();
  }, [searchParams]);

  const handleSave = async () => {
    if (!form.source_url || !form.target_url || !form.anchor_text) {
      error('Fyll i alla obligatoriska fält');
      return;
    }
    
    setSaving(true);
    try {
      await seoApi.createInternalLink({
        source_url: form.source_url,
        target_url: form.target_url,
        anchor_text: form.anchor_text,
        link_strength: parseInt(form.link_strength),
        is_auto_generated: false,
      });
      success('Länk skapad');
      resetForm();
      fetchLinks();
    } catch (err) {
      console.error('Failed to save link:', err);
      error('Kunde inte spara länk');
    } finally {
      setSaving(false);
    }
  };

  const handleDelete = async () => {
    if (!linkToDelete) return;
    try {
      await seoApi.deleteInternalLink(linkToDelete.id);
      success('Länk raderad');
      fetchLinks();
    } catch (err) {
      error('Kunde inte radera länk');
    } finally {
      setLinkToDelete(null);
    }
  };

  const resetForm = () => {
    setShowForm(false);
    setForm({
      source_url: '',
      target_url: '',
      anchor_text: '',
      link_strength: '5',
    });
  };

  const handleGenerateAll = async () => {
    setGenerating(true);
    try {
      const result = await seoApi.generateAllLinks();
      success(result.message);
      // Go back to page 1 after generating
      const params = new URLSearchParams(searchParams.toString());
      params.set('page', '1');
      router.push(`${pathname}?${params.toString()}`);
    } catch (err) {
      console.error('Failed to generate links:', err);
      error('Kunde inte generera länkar. Kontrollera att det finns publicerade sidor och artiklar.');
    } finally {
      setGenerating(false);
    }
  };

  const handleFilterChange = (value: string) => {
    setFilterAutoGenerated(value);
    updateUrl('filter', value);
  };

  return (
    <div className="min-h-screen bg-[var(--dark-900)]">
      <div className="py-4 sm:py-8 px-0 space-y-6">
        {/* Header */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 px-4 sm:px-0">
          <div>
            <Link href="/admin/super/seo" className="inline-flex items-center text-sm text-[var(--brand-light)]/50 hover:text-[var(--brand-light)] mb-2">
              <ArrowLeft className="w-4 h-4 mr-1" /> Tillbaka till SEO
            </Link>
            <div className="flex items-center gap-3 mb-1">
              <div className="w-10 h-10 rounded-xl bg-[var(--brand-peach)] flex items-center justify-center">
                <Link2 className="w-5 h-5 text-[var(--dark-900)]" />
              </div>
              <h1 className="text-2xl sm:text-3xl font-bold text-[var(--brand-light)]">Interna länkar</h1>
            </div>
            <p className="text-[var(--brand-light)]/50 text-sm pl-[52px]">
              Hantera intern länkstruktur för bättre SEO
            </p>
          </div>
          <div className="flex items-center gap-3">
            <button
              onClick={handleGenerateAll}
              disabled={generating}
              className="flex items-center gap-2 bg-[var(--brand-purple)] hover:bg-[var(--brand-purple)]/90 text-white font-bold rounded-xl px-6 py-3 transition-all disabled:opacity-50"
            >
              {generating ? (
                <Loader2 className="w-4 h-4 animate-spin" />
              ) : (
                <Wand2 className="w-4 h-4" />
              )}
              {generating ? 'Genererar...' : 'Generera alla'}
            </button>
            <button
              onClick={() => setShowForm(true)}
              className="flex items-center gap-2 bg-[var(--brand-primary)] hover:bg-[var(--brand-primary)]/90 text-[var(--dark-900)] font-bold rounded-xl px-6 py-3 transition-all"
            >
              <Plus className="w-4 h-4" />
              Lägg till länk
            </button>
          </div>
        </div>

        {/* Stats */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 sm:gap-4 px-4 sm:px-0">
          <div className="bg-[var(--dark-700)] rounded-xl p-4 border border-[var(--dark-500)]">
            <span className="text-xs font-medium text-[var(--brand-light)]/70 block mb-1">Totalt</span>
            <div className="text-2xl font-bold text-[var(--brand-peach)]">{totalCount}</div>
          </div>
          <div className="bg-[var(--dark-700)] rounded-xl p-4 border border-[var(--dark-500)]">
            <span className="text-xs font-medium text-[var(--brand-light)]/70 block mb-1">På denna sida</span>
            <div className="text-2xl font-bold text-[var(--brand-primary)]">
              {links.length}
            </div>
          </div>
          <div className="bg-[var(--dark-700)] rounded-xl p-4 border border-[var(--dark-500)]">
            <span className="text-xs font-medium text-[var(--brand-light)]/70 block mb-1">Sida</span>
            <div className="text-2xl font-bold text-[var(--brand-purple)]">
              {currentPage} / {totalPages || 1}
            </div>
          </div>
          <div className="bg-[var(--dark-700)] rounded-xl p-4 border border-[var(--dark-500)]">
            <span className="text-xs font-medium text-[var(--brand-light)]/70 block mb-1">Hög prioritet</span>
            <div className="text-2xl font-bold text-[var(--brand-green)]">
              {links.filter(l => l.link_strength >= 7).length}
            </div>
          </div>
        </div>

        {/* Info Box */}
        <div className="px-4 sm:px-0">
          <div className="bg-[var(--dark-800)] rounded-xl border border-[var(--dark-600)] p-4">
            <div className="flex items-start gap-3">
              <div className="w-8 h-8 rounded-lg bg-[var(--brand-purple)]/20 flex items-center justify-center flex-shrink-0">
                <Wand2 className="h-4 w-4 text-[var(--brand-purple)]" />
              </div>
              <div>
                <h3 className="font-medium text-[var(--brand-light)] mb-1">Automatisk länkgenerering</h3>
                <p className="text-sm text-[var(--brand-light)]/60">
                  Klicka på <strong>"Generera alla"</strong> för att automatiskt skapa interna länkar mellan dina publicerade sidor och artiklar. 
                  Systemet analyserar innehåll och skapar länkar baserat på geografisk närhet, gemensamma sökord och målgrupper.
                  Länkstyrka (1-10) anger hur viktig länken är för SEO.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Search & Filters */}
        <div className="flex flex-col sm:flex-row gap-3 px-4 sm:px-0">
          <div className="flex-1 bg-[var(--dark-800)] rounded-xl border border-[var(--dark-600)] px-4 py-3 flex items-center gap-3">
            <Search className="h-5 w-5 text-[var(--brand-light)]/40 flex-shrink-0" />
            <input 
              ref={searchInputRef}
              type="text"
              placeholder="Sök i länkar..."
              className="flex-1 bg-transparent text-[var(--brand-light)] placeholder-[var(--brand-light)]/40 outline-none text-base"
              value={searchInput}
              onChange={e => setSearchInput(e.target.value)}
            />
            {searchInput && (
              <button 
                onClick={() => setSearchInput('')}
                className="text-[var(--brand-light)]/40 hover:text-[var(--brand-light)] transition-colors"
              >
                <X className="h-4 w-4" />
              </button>
            )}
          </div>
          <select
            value={filterAutoGenerated}
            onChange={e => handleFilterChange(e.target.value)}
            className="bg-[var(--dark-700)] border border-[var(--dark-500)] rounded-xl px-4 py-3 text-[var(--brand-light)] outline-none"
          >
            <option value="">Alla länkar</option>
            <option value="false">Manuella</option>
            <option value="true">Auto-genererade</option>
          </select>
        </div>

        {/* Links List */}
        {loading ? (
          <div className="space-y-3 px-4 sm:px-0">
            {[...Array(5)].map((_, i) => (
              <div key={i} className="bg-[var(--dark-800)] rounded-xl border border-[var(--dark-600)] p-4">
                <Skeleton className="h-5 w-48 mb-2" />
                <Skeleton className="h-4 w-32" />
              </div>
            ))}
          </div>
        ) : links.length === 0 ? (
          <div className="text-center py-16 bg-[var(--dark-800)] rounded-none sm:rounded-xl border-y sm:border border-[var(--dark-600)] mx-4 sm:mx-0">
            <Link2 className="w-12 h-12 mx-auto text-[var(--brand-light)]/20 mb-4" />
            <p className="text-[var(--brand-light)]/50 mb-2">
              {searchParams.get('search') || searchParams.get('filter') 
                ? 'Inga länkar matchar filtren' 
                : 'Inga interna länkar ännu'}
            </p>
            {!searchParams.get('search') && !searchParams.get('filter') && (
              <button
                onClick={() => setShowForm(true)}
                className="text-[var(--brand-primary)] hover:underline text-sm font-medium"
              >
                Lägg till din första länk
              </button>
            )}
          </div>
        ) : (
          <div className="space-y-2 px-4 sm:px-0">
            {links.map((link) => (
              <div
                key={link.id}
                className="bg-[var(--dark-800)] rounded-xl border border-[var(--dark-600)] p-4 hover:border-[var(--dark-500)] transition-all"
              >
                <div className="flex items-center justify-between gap-4">
                  <div className="flex-1 min-w-0">
                    <div className="flex flex-wrap items-center gap-2 mb-2">
                      <span className="font-medium text-[var(--brand-light)]">"{link.anchor_text}"</span>
                      {link.is_auto_generated ? (
                        <span className="px-2 py-0.5 text-xs rounded-full font-medium bg-[var(--brand-purple)]/20 text-[var(--brand-purple)]">
                          Auto
                        </span>
                      ) : (
                        <span className="px-2 py-0.5 text-xs rounded-full font-medium bg-[var(--brand-primary)]/20 text-[var(--brand-primary)]">
                          Manuell
                        </span>
                      )}
                      <span className={`px-2 py-0.5 text-xs rounded-full font-medium ${
                        link.link_strength >= 7 
                          ? 'bg-[var(--brand-green)]/20 text-[var(--brand-green)]'
                          : link.link_strength >= 4
                          ? 'bg-[var(--brand-peach)]/20 text-[var(--brand-peach)]'
                          : 'bg-[var(--dark-600)] text-[var(--brand-light)]/50'
                      }`}>
                        Styrka: {link.link_strength}
                      </span>
                    </div>
                    <div className="flex flex-col sm:flex-row sm:items-center gap-2 text-sm text-[var(--brand-light)]/50">
                      <span className="truncate">Från: <strong className="text-[var(--brand-light)]/70">{link.source_url}</strong></span>
                      <span className="hidden sm:inline">→</span>
                      <span className="truncate">Till: <strong className="text-[var(--brand-light)]/70">{link.target_url}</strong></span>
                    </div>
                  </div>
                  
                  <div className="flex items-center gap-1 flex-shrink-0">
                    <a
                      href={link.target_url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="w-9 h-9 rounded-lg bg-[var(--dark-600)] text-[var(--brand-light)]/60 hover:text-[var(--brand-blue)] hover:bg-[var(--brand-blue)]/20 transition-all flex items-center justify-center"
                    >
                      <ExternalLink className="w-4 h-4" />
                    </a>
                    <button
                      onClick={() => setLinkToDelete(link)}
                      className="w-9 h-9 rounded-lg bg-[var(--dark-600)] text-[var(--brand-light)]/60 hover:text-[var(--brand-red)] hover:bg-[var(--brand-red)]/20 transition-all flex items-center justify-center"
                    >
                      <Trash2 className="w-4 h-4" />
                    </button>
                  </div>
                </div>
              </div>
            ))}
            
            {/* Pagination */}
            {totalPages > 1 && (
              <div className="flex items-center justify-center gap-3 py-6">
                <button 
                  disabled={currentPage === 1} 
                  onClick={() => handlePageChange(currentPage - 1)}
                  className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium bg-[var(--dark-700)] border border-[var(--dark-500)] text-[var(--brand-light)]/70 hover:text-[var(--brand-light)] hover:bg-[var(--dark-600)] transition-all disabled:opacity-40 disabled:cursor-not-allowed"
                >
                  <ChevronLeft className="w-4 h-4" />
                  Föregående
                </button>
                <div className="text-sm text-[var(--brand-light)]/50">
                  Sida <span className="text-[var(--brand-primary)] font-semibold">{currentPage}</span> av <span className="text-[var(--brand-primary)] font-semibold">{totalPages}</span>
                </div>
                <button 
                  disabled={currentPage >= totalPages} 
                  onClick={() => handlePageChange(currentPage + 1)}
                  className="flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium bg-[var(--dark-700)] border border-[var(--dark-500)] text-[var(--brand-light)]/70 hover:text-[var(--brand-light)] hover:bg-[var(--dark-600)] transition-all disabled:opacity-40 disabled:cursor-not-allowed"
                >
                  Nästa
                  <ChevronRight className="w-4 h-4" />
                </button>
              </div>
            )}
          </div>
        )}

        {/* Form Modal */}
        {showForm && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70">
            <div className="bg-[var(--dark-800)] rounded-2xl w-full max-w-md border border-[var(--dark-600)] overflow-hidden">
              <div className="flex items-center justify-between px-6 py-4 border-b border-[var(--dark-600)]">
                <h3 className="text-lg font-semibold text-[var(--brand-light)]">
                  Lägg till intern länk
                </h3>
                <button 
                  onClick={resetForm}
                  className="text-[var(--brand-light)]/40 hover:text-[var(--brand-light)] transition-colors p-2 rounded-lg hover:bg-[var(--dark-700)]"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              <div className="p-6 space-y-4">
                <div>
                  <label className="block text-sm font-medium text-[var(--brand-light)]/70 mb-2">Källsida (URL) *</label>
                  <input
                    type="text"
                    value={form.source_url}
                    onChange={(e) => setForm({ ...form, source_url: e.target.value })}
                    className="w-full px-4 py-3 bg-[var(--dark-700)] border-2 border-[var(--dark-500)] rounded-xl text-[var(--brand-light)] placeholder-[var(--brand-light)]/40 outline-none focus:border-[var(--brand-primary)] transition-colors"
                    placeholder="/kommun/stockholm"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-[var(--brand-light)]/70 mb-2">Målsida (URL) *</label>
                  <input
                    type="text"
                    value={form.target_url}
                    onChange={(e) => setForm({ ...form, target_url: e.target.value })}
                    className="w-full px-4 py-3 bg-[var(--dark-700)] border-2 border-[var(--dark-500)] rounded-xl text-[var(--brand-light)] placeholder-[var(--brand-light)]/40 outline-none focus:border-[var(--brand-primary)] transition-colors"
                    placeholder="/artiklar/fritidsgard-guide"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-[var(--brand-light)]/70 mb-2">Ankartext *</label>
                  <input
                    type="text"
                    value={form.anchor_text}
                    onChange={(e) => setForm({ ...form, anchor_text: e.target.value })}
                    className="w-full px-4 py-3 bg-[var(--dark-700)] border-2 border-[var(--dark-500)] rounded-xl text-[var(--brand-light)] placeholder-[var(--brand-light)]/40 outline-none focus:border-[var(--brand-primary)] transition-colors"
                    placeholder="Läs vår guide om fritidsgårdar"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-[var(--brand-light)]/70 mb-2">Länkstyrka (1-10)</label>
                  <input
                    type="range"
                    min="1"
                    max="10"
                    value={form.link_strength}
                    onChange={(e) => setForm({ ...form, link_strength: e.target.value })}
                    className="w-full"
                  />
                  <div className="flex justify-between text-xs text-[var(--brand-light)]/50 mt-1">
                    <span>Låg</span>
                    <span className="font-medium text-[var(--brand-primary)]">{form.link_strength}</span>
                    <span>Hög</span>
                  </div>
                </div>
              </div>

              <div className="flex justify-end gap-3 px-6 py-4 border-t border-[var(--dark-600)] bg-[var(--dark-700)]/50">
                <button
                  onClick={resetForm}
                  className="px-4 py-2.5 text-[var(--brand-light)]/60 hover:text-[var(--brand-light)] hover:bg-[var(--dark-700)] rounded-xl transition-all font-medium"
                >
                  Avbryt
                </button>
                <button
                  onClick={handleSave}
                  disabled={saving || !form.source_url || !form.target_url || !form.anchor_text}
                  className="flex items-center gap-2 bg-[var(--brand-primary)] hover:bg-[var(--brand-primary)]/90 text-[var(--dark-900)] font-bold rounded-xl px-6 py-2.5 transition-all disabled:opacity-50"
                >
                  {saving && <Loader2 className="w-4 h-4 animate-spin" />}
                  Lägg till
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Delete Confirmation */}
        <ConfirmationModal
          isVisible={!!linkToDelete}
          onClose={() => setLinkToDelete(null)}
          onConfirm={handleDelete}
          title="Radera länk"
          message={`Är du säker på att du vill radera länken med ankartext "${linkToDelete?.anchor_text}"?`}
          confirmButtonText="Radera"
          cancelButtonText="Avbryt"
          variant="danger"
          darkMode={true}
        />
      </div>
    </div>
  );
}

export default function InternalLinksPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-[var(--dark-900)] flex items-center justify-center">
        <Loader2 className="w-8 h-8 animate-spin text-[var(--brand-primary)]" />
      </div>
    }>
      <InternalLinksContent />
    </Suspense>
  );
}
