# Generated by Django 5.2.8 on 2025-12-25 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0009_club_slug_municipality_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('MONTHLY', 'Monthly Summary'), ('YEARLY', 'Yearly Summary'), ('CUSTOM', 'Custom Report')], default='CUSTOM', max_length=20)),
                ('date_range_start', models.DateTimeField()),
                ('date_range_end', models.DateTimeField()),
                ('file', models.FileField(blank=True, help_text='PDF or Excel export', null=True, upload_to='reports/generated/')),
                ('data_snapshot', models.JSONField(default=dict, help_text='Raw JSON metrics at the time of generation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(blank=True, help_text='Null if Municipality/Global report', null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.club')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
