# Generated by Django 5.2.8 on 2025-12-25 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(help_text='e.g. 1.0. Incrementing this forces users to re-accept.', max_length=20)),
                ('title', models.CharField(default='We use cookies', max_length=255)),
                ('description', models.TextField(help_text='Main banner text')),
                ('policy_text', models.TextField(help_text='Full rich text policy')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('media', models.FileField(upload_to='cms/features/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video (WebM/MP4)'), ('lottie', 'Lottie Animation (JSON)')], default='image', max_length=20)),
                ('alt_text', models.CharField(help_text='Accessibility text', max_length=255)),
                ('layout', models.CharField(choices=[('left', 'Text Left, Media Right'), ('right', 'Text Right, Media Left'), ('grid', 'Grid Item')], default='left', max_length=20)),
                ('animation_type', models.CharField(default='fade-up', help_text='Frontend animation class', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('page_type', models.CharField(choices=[('standard', 'Standard Page'), ('creative', 'Creative Showcase')], default='standard', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Rich text content')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='cms/hero/')),
                ('show_hero', models.BooleanField(default=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='cms/seo/')),
                ('ai_description', models.TextField(blank=True, help_text='A specific description optimized for AI search engines and LLMs.')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('external_url', models.URLField(blank=True, help_text='Use this if linking to an external site')),
                ('location', models.CharField(choices=[('header', 'Top Navigation'), ('footer', 'Footer'), ('none', 'No Menu (Direct Link)')], default='none', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='cms.menuitem')),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='cms.page')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
