# Generated by Django 5.2.8 on 2025-12-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='features',
            field=models.ManyToManyField(blank=True, help_text='Select features to display on creative pages', related_name='pages', to='cms.featureshowcase'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='location',
            field=models.CharField(choices=[('header', 'Top Navigation'), ('footer', 'Public Footer'), ('community_footer', 'Community Footer (Logged-in Users)'), ('none', 'No Menu (Direct Link)')], default='none', max_length=20),
        ),
    ]
