# Generated by Django 5.2.8 on 2025-12-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_page_features_alter_menuitem_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureshowcase',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Accessibility text', max_length=255),
        ),
        migrations.AlterField(
            model_name='featureshowcase',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='cms/features/'),
        ),
    ]
