# Generated by Django 5.2.8 on 2025-12-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_add_pagefeature_through_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='cms/authors/'),
        ),
        migrations.AddField(
            model_name='page',
            name='author_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='author_title',
            field=models.CharField(blank=True, help_text="e.g. 'Content Manager'", max_length=255),
        ),
        migrations.AddField(
            model_name='page',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Short description shown in hero'),
        ),
        migrations.AddField(
            model_name='page',
            name='show_toc',
            field=models.BooleanField(default=False, help_text='Show table of contents sidebar'),
        ),
        migrations.AddField(
            model_name='page',
            name='table_of_contents',
            field=models.JSONField(blank=True, help_text="Optional table of contents. Format: [{title: 'Section', anchor: 'section-id'}]", null=True),
        ),
    ]
