# Generated by Django 5.2.8 on 2025-12-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_page_author_image_page_author_name_page_author_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='hero_tagline',
            field=models.CharField(blank=True, help_text='Sub-hero tagline displayed below the title', max_length=255),
        ),
    ]
