# Generated by Django 5.2.8 on 2025-12-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_page_hero_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pricing FAQ',
                'verbose_name_plural': 'Pricing FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Choose Your Plan', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, help_text='Short description below the title')),
                ('hero_tagline', models.CharField(blank=True, help_text="Small text above the title (e.g., 'Simple Pricing')", max_length=255)),
                ('cta_title', models.CharField(blank=True, default='Ready to Get Started?', max_length=255)),
                ('cta_description', models.TextField(blank=True)),
                ('cta_button_text', models.CharField(blank=True, default='Contact Us', max_length=100)),
                ('cta_button_url', models.URLField(blank=True, help_text='Link for the CTA button')),
                ('trust_section_title', models.CharField(blank=True, default='Trusted by Municipalities', max_length=255)),
                ('trust_section_description', models.TextField(blank=True)),
                ('meta_title', models.CharField(blank=True, help_text='Page title for SEO', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='Meta description for search engines')),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title for social sharing', max_length=255)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description')),
                ('og_image', models.ImageField(blank=True, help_text='Image for social sharing', null=True, upload_to='cms/seo/')),
                ('ai_description', models.TextField(blank=True, help_text='Description optimized for AI search engines')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pricing Page Content',
                'verbose_name_plural': 'Pricing Page Content',
            },
        ),
    ]
