# Generated by Django 5.2.8 on 2025-12-29 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_add_pricing_page_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingpagecontent',
            name='trust_stat_active_users',
            field=models.CharField(blank=True, default='100K+', help_text="Number of active users (e.g., '100K+')", max_length=50),
        ),
        migrations.AddField(
            model_name='pricingpagecontent',
            name='trust_stat_municipalities',
            field=models.CharField(blank=True, default='50+', help_text="Number of municipalities (e.g., '50+')", max_length=50),
        ),
        migrations.AddField(
            model_name='pricingpagecontent',
            name='trust_stat_satisfaction',
            field=models.CharField(blank=True, default='4.9/5', help_text="Satisfaction rating (e.g., '4.9/5')", max_length=50),
        ),
        migrations.AddField(
            model_name='pricingpagecontent',
            name='trust_stat_uptime',
            field=models.CharField(blank=True, default='99.9%', help_text="Uptime percentage (e.g., '99.9%')", max_length=50),
        ),
    ]
