# Generated by Django 5.2.8 on 2025-12-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_pricingpagecontent_trust_stat_active_users_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Kontakta oss', max_length=255)),
                ('hero_subtitle', models.TextField(blank=True, default='Vi hjälper dig gärna med frågor om Ungdomsappen')),
                ('contact_email', models.EmailField(default='support@ungdomsappen.se', max_length=254)),
                ('response_time_text', models.CharField(blank=True, default='Vi svarar vanligtvis inom 24 timmar', max_length=255)),
                ('form_title', models.CharField(blank=True, default='Skicka ett meddelande', max_length=255)),
                ('form_description', models.TextField(blank=True, default='Fyll i formuläret nedan så återkommer vi så snart som möjligt')),
                ('success_title', models.CharField(blank=True, default='Tack för ditt meddelande!', max_length=255)),
                ('success_message', models.TextField(blank=True, default='Vi har tagit emot ditt meddelande och återkommer så snart som möjligt.')),
                ('info_title', models.CharField(blank=True, default='Annan information', max_length=255)),
                ('info_content', models.TextField(blank=True, help_text='Additional information shown on the contact page (supports markdown)')),
                ('meta_title', models.CharField(blank=True, default='Kontakt - Ungdomsappen', max_length=255)),
                ('meta_description', models.TextField(blank=True, default='Kontakta Ungdomsappen för frågor om vår plattform för ungdomsverksamhet.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Page Content',
                'verbose_name_plural': 'Contact Page Content',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_replied', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
