# Generated by Django 5.2.8 on 2026-01-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_contactpagecontent_contactsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boilerplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal name for the template', max_length=255)),
                ('usage', models.CharField(choices=[('terms_and_conditions', 'Villkor'), ('club_policies', 'Klubbregler'), ('privacy_policy', 'Integritetspolicy'), ('general', 'Allmän')], default='general', help_text='Where this template can be used', max_length=50)),
                ('content', models.TextField(help_text='The template content (supports HTML)')),
                ('description', models.TextField(blank=True, help_text='Description of what this template is for')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Boilerplate',
                'verbose_name_plural': 'Boilerplates',
                'ordering': ['order', 'name'],
            },
        ),
    ]
