# Generated by Django 5.2.8 on 2026-01-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_add_boilerplate_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boilerplate',
            name='content',
            field=models.TextField(blank=True, default='', help_text='The template content (supports HTML)'),
        ),
    ]
