# Generated by Django 5.2.8 on 2026-01-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_allow_blank_boilerplate_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpagecontent',
            name='language',
            field=models.CharField(choices=[('sv', 'Svenska'), ('en', 'English'), ('da', 'Dansk'), ('nb', 'Norsk'), ('fi', 'Suomi'), ('ar', 'العربية'), ('so', 'Soomaali'), ('prs', 'دری')], db_index=True, default='sv', help_text='Language for this contact page content', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='cookieconsent',
            name='language',
            field=models.CharField(choices=[('sv', 'Svenska'), ('en', 'English'), ('da', 'Dansk'), ('nb', 'Norsk'), ('fi', 'Suomi'), ('ar', 'العربية'), ('so', 'Soomaali'), ('prs', 'دری')], db_index=True, default='sv', help_text='Language for this cookie consent', max_length=10),
        ),
        migrations.AddField(
            model_name='featureshowcase',
            name='language',
            field=models.CharField(choices=[('sv', 'Svenska'), ('en', 'English'), ('da', 'Dansk'), ('nb', 'Norsk'), ('fi', 'Suomi'), ('ar', 'العربية'), ('so', 'Soomaali'), ('prs', 'دری')], db_index=True, default='sv', help_text='Language for this feature', max_length=10),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='language',
            field=models.CharField(choices=[('sv', 'Svenska'), ('en', 'English'), ('da', 'Dansk'), ('nb', 'Norsk'), ('fi', 'Suomi'), ('ar', 'العربية'), ('so', 'Soomaali'), ('prs', 'دری')], db_index=True, default='sv', help_text='Language for this menu item', max_length=10),
        ),
        migrations.AddField(
            model_name='page',
            name='language',
            field=models.CharField(choices=[('sv', 'Svenska'), ('en', 'English'), ('da', 'Dansk'), ('nb', 'Norsk'), ('fi', 'Suomi'), ('ar', 'العربية'), ('so', 'Soomaali'), ('prs', 'دری')], db_index=True, default='sv', help_text='Language for this page', max_length=10),
        ),
        migrations.AddField(
            model_name='pricingfaq',
            name='language',
            field=models.CharField(choices=[('sv', 'Svenska'), ('en', 'English'), ('da', 'Dansk'), ('nb', 'Norsk'), ('fi', 'Suomi'), ('ar', 'العربية'), ('so', 'Soomaali'), ('prs', 'دری')], db_index=True, default='sv', help_text='Language for this FAQ', max_length=10),
        ),
        migrations.AddField(
            model_name='pricingpagecontent',
            name='language',
            field=models.CharField(choices=[('sv', 'Svenska'), ('en', 'English'), ('da', 'Dansk'), ('nb', 'Norsk'), ('fi', 'Suomi'), ('ar', 'العربية'), ('so', 'Soomaali'), ('prs', 'دری')], db_index=True, default='sv', help_text='Language for this pricing page content', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='cookieconsent',
            unique_together={('language', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('slug', 'language')},
        ),
    ]
