# Generated by Django 5.2.8 on 2025-12-28 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('deletion_warning_first', 'Deletion Warning (First - 30 days)'), ('deletion_warning_final', 'Deletion Warning (Final - 7 days)'), ('account_deleted', 'Account Deleted Confirmation'), ('new_message', 'New Message Received'), ('new_event', 'New Event Published'), ('event_reminder', 'Event Reminder'), ('event_cancelled', 'Event Cancelled'), ('welcome', 'Welcome Email'), ('guardian_link_request', 'Guardian Link Request'), ('guardian_link_approved', 'Guardian Link Approved'), ('reward_earned', 'Reward Earned'), ('new_questionnaire', 'New Questionnaire Available')], help_text='The type of email this template is for', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Human-readable name for this template', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of when this email is sent')),
                ('available_variables', models.JSONField(default=list, help_text='List of available template variables with descriptions')),
                ('is_active', models.BooleanField(default=True, help_text='If disabled, emails of this type will not be sent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Template',
                'verbose_name_plural': 'Email Templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(help_text='Email address the email was sent to', max_length=254)),
                ('template_type', models.CharField(blank=True, help_text='Template type (preserved even if template is deleted)', max_length=50)),
                ('subject', models.CharField(help_text='Subject line of the sent email', max_length=200)),
                ('body_preview', models.TextField(blank=True, help_text='First 500 characters of the email body')),
                ('language', models.CharField(help_text='Language the email was sent in', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if sending failed')),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Variable data used for rendering (for debugging)')),
                ('sent_at', models.DateTimeField(blank=True, help_text='When the email was actually sent', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, help_text='The user who received this email (null if user was deleted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='The template used for this email', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='emails.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('sv', 'Swedish'), ('en', 'English'), ('ar', 'Arabic'), ('da', 'Danish'), ('fi', 'Finnish'), ('nb', 'Norwegian'), ('prs', 'Dari/Persian'), ('so', 'Somali')], help_text='Language code for this translation', max_length=10)),
                ('subject', models.CharField(help_text='Email subject line (can include variables like {{user.first_name}})', max_length=200)),
                ('body_html', models.TextField(help_text='HTML version of the email body')),
                ('body_text', models.TextField(blank=True, help_text='Plain text version of the email body (auto-generated if empty)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='emails.emailtemplate')),
            ],
            options={
                'verbose_name': 'Email Template Translation',
                'verbose_name_plural': 'Email Template Translations',
                'ordering': ['template', 'language'],
                'unique_together': {('template', 'language')},
            },
        ),
    ]
