# Generated by Django

from django.db import migrations


def create_default_templates(apps, schema_editor):
    """Create default email templates with Swedish and English translations."""
    EmailTemplate = apps.get_model('emails', 'EmailTemplate')
    EmailTemplateTranslation = apps.get_model('emails', 'EmailTemplateTranslation')

    # Define templates with their translations
    templates = [
        # ===== DATA RETENTION =====
        {
            'type': 'deletion_warning_first',
            'name': 'Deletion Warning (First - 30 days)',
            'description': 'Sent 30 days before account deletion due to inactivity',
            'available_variables': [
                {'name': 'user.first_name', 'description': 'User\'s first name'},
                {'name': 'user.full_name', 'description': 'User\'s full name'},
                {'name': 'days_left', 'description': 'Days until account deletion'},
                {'name': 'deletion_date', 'description': 'Date when account will be deleted'},
                {'name': 'app_name', 'description': 'Application name (Ungdomsappen)'},
            ],
            'translations': {
                'sv': {
                    'subject': 'Ditt konto kommer att raderas om {{days_left}} dagar',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333;">Hej {{user.first_name}}!</h1>
    
    <p>Vi saknar dig på {{app_name}}! Ditt konto har varit inaktivt ett tag och enligt våra dataskyddsregler (GDPR) kommer vi att radera ditt konto och all tillhörande data om <strong>{{days_left}} dagar</strong>.</p>
    
    <p><strong>Datum för radering:</strong> {{deletion_date}}</p>
    
    <p>Om du vill behålla ditt konto behöver du bara logga in före detta datum, så återställs din inaktivitetsperiod.</p>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Logga in nu</a>
    </div>
    
    <p style="color: #666; font-size: 14px;">Om du inte längre vill använda {{app_name}} behöver du inte göra något - ditt konto kommer automatiskt att raderas.</p>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">Detta meddelande skickades från {{app_name}}. Om du har frågor, kontakta oss på {{support_email}}.</p>
</div>
''',
                },
                'en': {
                    'subject': 'Your account will be deleted in {{days_left}} days',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333;">Hi {{user.first_name}}!</h1>
    
    <p>We miss you at {{app_name}}! Your account has been inactive for a while, and according to our data protection policies (GDPR), we will delete your account and all associated data in <strong>{{days_left}} days</strong>.</p>
    
    <p><strong>Deletion date:</strong> {{deletion_date}}</p>
    
    <p>If you want to keep your account, simply log in before this date and your inactivity period will be reset.</p>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Log in now</a>
    </div>
    
    <p style="color: #666; font-size: 14px;">If you no longer wish to use {{app_name}}, you don't need to do anything - your account will be automatically deleted.</p>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">This message was sent from {{app_name}}. If you have questions, contact us at {{support_email}}.</p>
</div>
''',
                },
            },
        },
        {
            'type': 'deletion_warning_final',
            'name': 'Deletion Warning (Final - 7 days)',
            'description': 'Final warning sent 7 days before account deletion',
            'available_variables': [
                {'name': 'user.first_name', 'description': 'User\'s first name'},
                {'name': 'days_left', 'description': 'Days until account deletion'},
                {'name': 'deletion_date', 'description': 'Date when account will be deleted'},
                {'name': 'app_name', 'description': 'Application name'},
            ],
            'translations': {
                'sv': {
                    'subject': '⚠️ Sista varningen: Ditt konto raderas om {{days_left}} dagar',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #dc2626;">⚠️ Sista varningen, {{user.first_name}}!</h1>
    
    <p style="font-size: 18px;">Ditt konto på {{app_name}} kommer att <strong>raderas permanent om {{days_left}} dagar</strong>.</p>
    
    <div style="background-color: #fef2f2; border: 1px solid #fecaca; border-radius: 8px; padding: 16px; margin: 20px 0;">
        <p style="margin: 0; color: #dc2626;"><strong>Raderingsdatum:</strong> {{deletion_date}}</p>
    </div>
    
    <p>När ditt konto raderas kommer all din data att försvinna permanent, inklusive:</p>
    <ul>
        <li>Din profil och inställningar</li>
        <li>Dina inlägg och meddelanden</li>
        <li>Din aktivitetshistorik</li>
    </ul>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se" style="background-color: #dc2626; color: white; padding: 14px 28px; text-decoration: none; border-radius: 6px; display: inline-block; font-weight: bold;">Logga in för att behålla ditt konto</a>
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | Kontakta oss: {{support_email}}</p>
</div>
''',
                },
                'en': {
                    'subject': '⚠️ Final warning: Your account will be deleted in {{days_left}} days',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #dc2626;">⚠️ Final warning, {{user.first_name}}!</h1>
    
    <p style="font-size: 18px;">Your account on {{app_name}} will be <strong>permanently deleted in {{days_left}} days</strong>.</p>
    
    <div style="background-color: #fef2f2; border: 1px solid #fecaca; border-radius: 8px; padding: 16px; margin: 20px 0;">
        <p style="margin: 0; color: #dc2626;"><strong>Deletion date:</strong> {{deletion_date}}</p>
    </div>
    
    <p>When your account is deleted, all your data will be permanently lost, including:</p>
    <ul>
        <li>Your profile and settings</li>
        <li>Your posts and messages</li>
        <li>Your activity history</li>
    </ul>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se" style="background-color: #dc2626; color: white; padding: 14px 28px; text-decoration: none; border-radius: 6px; display: inline-block; font-weight: bold;">Log in to keep your account</a>
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | Contact us: {{support_email}}</p>
</div>
''',
                },
            },
        },
        {
            'type': 'account_deleted',
            'name': 'Account Deleted Confirmation',
            'description': 'Sent after account has been deleted/anonymized',
            'available_variables': [
                {'name': 'app_name', 'description': 'Application name'},
            ],
            'translations': {
                'sv': {
                    'subject': 'Ditt konto har raderats',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333;">Ditt konto har raderats</h1>
    
    <p>Ditt konto på {{app_name}} har nu raderats enligt våra dataskyddsregler (GDPR).</p>
    
    <p>All personlig data kopplad till ditt konto har tagits bort permanent.</p>
    
    <p>Om du vill använda {{app_name}} igen i framtiden är du välkommen att skapa ett nytt konto.</p>
    
    <p style="color: #666;">Tack för att du använde {{app_name}}!</p>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
                'en': {
                    'subject': 'Your account has been deleted',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333;">Your account has been deleted</h1>
    
    <p>Your account on {{app_name}} has been deleted according to our data protection policies (GDPR).</p>
    
    <p>All personal data associated with your account has been permanently removed.</p>
    
    <p>If you want to use {{app_name}} again in the future, you're welcome to create a new account.</p>
    
    <p style="color: #666;">Thank you for using {{app_name}}!</p>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
            },
        },
        
        # ===== NOTIFICATIONS =====
        {
            'type': 'new_message',
            'name': 'New Message Received',
            'description': 'Sent when user receives a new message',
            'available_variables': [
                {'name': 'user.first_name', 'description': 'User\'s first name'},
                {'name': 'message_sender', 'description': 'Name of who sent the message'},
                {'name': 'app_name', 'description': 'Application name'},
            ],
            'translations': {
                'sv': {
                    'subject': 'Du har fått ett nytt meddelande',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333;">Hej {{user.first_name}}!</h1>
    
    <p>Du har fått ett nytt meddelande från <strong>{{message_sender}}</strong> på {{app_name}}.</p>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se/messages" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Läs meddelandet</a>
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
                'en': {
                    'subject': 'You have a new message',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333;">Hi {{user.first_name}}!</h1>
    
    <p>You have received a new message from <strong>{{message_sender}}</strong> on {{app_name}}.</p>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se/messages" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Read message</a>
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
            },
        },
        {
            'type': 'new_event',
            'name': 'New Event Published',
            'description': 'Sent when a new event is published at user\'s club',
            'available_variables': [
                {'name': 'user.first_name', 'description': 'User\'s first name'},
                {'name': 'event_name', 'description': 'Name of the event'},
                {'name': 'event_date', 'description': 'Date of the event'},
                {'name': 'club.name', 'description': 'Club name'},
                {'name': 'app_name', 'description': 'Application name'},
            ],
            'translations': {
                'sv': {
                    'subject': 'Nytt event: {{event_name}}',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333;">Hej {{user.first_name}}!</h1>
    
    <p>Ett nytt event har publicerats på {{club.name}}!</p>
    
    <div style="background-color: #f3f4f6; border-radius: 8px; padding: 20px; margin: 20px 0;">
        <h2 style="margin: 0 0 10px 0; color: #6366f1;">{{event_name}}</h2>
        <p style="margin: 0; color: #666;">📅 {{event_date}}</p>
    </div>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se/events" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Visa event</a>
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
                'en': {
                    'subject': 'New event: {{event_name}}',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333;">Hi {{user.first_name}}!</h1>
    
    <p>A new event has been published at {{club.name}}!</p>
    
    <div style="background-color: #f3f4f6; border-radius: 8px; padding: 20px; margin: 20px 0;">
        <h2 style="margin: 0 0 10px 0; color: #6366f1;">{{event_name}}</h2>
        <p style="margin: 0; color: #666;">📅 {{event_date}}</p>
    </div>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se/events" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">View event</a>
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
            },
        },
        {
            'type': 'event_reminder',
            'name': 'Event Reminder',
            'description': 'Reminder sent before an event the user has registered for',
            'available_variables': [
                {'name': 'user.first_name', 'description': 'User\'s first name'},
                {'name': 'event_name', 'description': 'Name of the event'},
                {'name': 'event_date', 'description': 'Date and time of the event'},
                {'name': 'app_name', 'description': 'Application name'},
            ],
            'translations': {
                'sv': {
                    'subject': 'Påminnelse: {{event_name}} börjar snart!',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333;">Hej {{user.first_name}}!</h1>
    
    <p>Glöm inte att <strong>{{event_name}}</strong> börjar snart!</p>
    
    <div style="background-color: #fef3c7; border: 1px solid #fcd34d; border-radius: 8px; padding: 16px; margin: 20px 0;">
        <p style="margin: 0; font-size: 18px;">📅 {{event_date}}</p>
    </div>
    
    <p>Vi ser fram emot att se dig där!</p>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
                'en': {
                    'subject': 'Reminder: {{event_name}} starts soon!',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333;">Hi {{user.first_name}}!</h1>
    
    <p>Don't forget that <strong>{{event_name}}</strong> starts soon!</p>
    
    <div style="background-color: #fef3c7; border: 1px solid #fcd34d; border-radius: 8px; padding: 16px; margin: 20px 0;">
        <p style="margin: 0; font-size: 18px;">📅 {{event_date}}</p>
    </div>
    
    <p>We look forward to seeing you there!</p>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
            },
        },
        {
            'type': 'event_cancelled',
            'name': 'Event Cancelled',
            'description': 'Sent when an event the user registered for is cancelled',
            'available_variables': [
                {'name': 'user.first_name', 'description': 'User\'s first name'},
                {'name': 'event_name', 'description': 'Name of the cancelled event'},
                {'name': 'app_name', 'description': 'Application name'},
            ],
            'translations': {
                'sv': {
                    'subject': 'Event inställt: {{event_name}}',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333;">Hej {{user.first_name}},</h1>
    
    <p>Vi måste tyvärr meddela att eventet <strong>{{event_name}}</strong> har ställts in.</p>
    
    <p>Vi beklagar eventuella olägenheter detta kan medföra.</p>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se/events" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Se andra event</a>
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
                'en': {
                    'subject': 'Event cancelled: {{event_name}}',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333;">Hi {{user.first_name}},</h1>
    
    <p>We regret to inform you that the event <strong>{{event_name}}</strong> has been cancelled.</p>
    
    <p>We apologize for any inconvenience this may cause.</p>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se/events" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">See other events</a>
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
            },
        },
        
        # ===== MEMBERSHIP =====
        {
            'type': 'welcome',
            'name': 'Welcome Email',
            'description': 'Sent when a new user registers',
            'available_variables': [
                {'name': 'user.first_name', 'description': 'User\'s first name'},
                {'name': 'club.name', 'description': 'Club name (if applicable)'},
                {'name': 'app_name', 'description': 'Application name'},
            ],
            'translations': {
                'sv': {
                    'subject': 'Välkommen till {{app_name}}!',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #6366f1;">Välkommen, {{user.first_name}}! 🎉</h1>
    
    <p>Vi är glada att ha dig med oss på {{app_name}}!</p>
    
    <p>Här är några saker du kan göra för att komma igång:</p>
    <ul>
        <li>Uppdatera din profil</li>
        <li>Utforska event i ditt område</li>
        <li>Anslut med andra medlemmar</li>
    </ul>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Utforska appen</a>
    </div>
    
    <p>Har du frågor? Kontakta oss på {{support_email}}.</p>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}}</p>
</div>
''',
                },
                'en': {
                    'subject': 'Welcome to {{app_name}}!',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #6366f1;">Welcome, {{user.first_name}}! 🎉</h1>
    
    <p>We're glad to have you with us at {{app_name}}!</p>
    
    <p>Here are some things you can do to get started:</p>
    <ul>
        <li>Update your profile</li>
        <li>Explore events in your area</li>
        <li>Connect with other members</li>
    </ul>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Explore the app</a>
    </div>
    
    <p>Have questions? Contact us at {{support_email}}.</p>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}}</p>
</div>
''',
                },
            },
        },
        {
            'type': 'guardian_link_request',
            'name': 'Guardian Link Request',
            'description': 'Sent to guardian when a youth requests to link accounts',
            'available_variables': [
                {'name': 'user.first_name', 'description': 'Guardian\'s first name'},
                {'name': 'youth_name', 'description': 'Youth\'s name'},
                {'name': 'app_name', 'description': 'Application name'},
            ],
            'translations': {
                'sv': {
                    'subject': 'Förfrågan om koppling från {{youth_name}}',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333;">Hej {{user.first_name}}!</h1>
    
    <p><strong>{{youth_name}}</strong> har begärt att koppla sitt konto till ditt på {{app_name}}.</p>
    
    <p>Logga in på appen för att godkänna eller avvisa denna begäran.</p>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Hantera begäran</a>
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
                'en': {
                    'subject': 'Link request from {{youth_name}}',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333;">Hi {{user.first_name}}!</h1>
    
    <p><strong>{{youth_name}}</strong> has requested to link their account to yours on {{app_name}}.</p>
    
    <p>Log in to the app to approve or reject this request.</p>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Manage request</a>
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
            },
        },
        {
            'type': 'guardian_link_approved',
            'name': 'Guardian Link Approved',
            'description': 'Sent to youth when guardian approves the link',
            'available_variables': [
                {'name': 'user.first_name', 'description': 'Youth\'s first name'},
                {'name': 'guardian_name', 'description': 'Guardian\'s name'},
                {'name': 'app_name', 'description': 'Application name'},
            ],
            'translations': {
                'sv': {
                    'subject': '✓ Din koppling till {{guardian_name}} har godkänts',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #16a34a;">Godkänt! ✓</h1>
    
    <p>Hej {{user.first_name}}!</p>
    
    <p><strong>{{guardian_name}}</strong> har godkänt din begäran om koppling på {{app_name}}.</p>
    
    <p>Du är nu kopplad och kan börja använda appen fullt ut!</p>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se" style="background-color: #16a34a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Öppna appen</a>
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
                'en': {
                    'subject': '✓ Your link to {{guardian_name}} has been approved',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #16a34a;">Approved! ✓</h1>
    
    <p>Hi {{user.first_name}}!</p>
    
    <p><strong>{{guardian_name}}</strong> has approved your link request on {{app_name}}.</p>
    
    <p>You are now linked and can start using the app fully!</p>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se" style="background-color: #16a34a; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Open the app</a>
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
            },
        },
        
        # ===== REWARDS =====
        {
            'type': 'reward_earned',
            'name': 'Reward Earned',
            'description': 'Sent when user earns a new reward',
            'available_variables': [
                {'name': 'user.first_name', 'description': 'User\'s first name'},
                {'name': 'reward_name', 'description': 'Name of the reward'},
                {'name': 'app_name', 'description': 'Application name'},
            ],
            'translations': {
                'sv': {
                    'subject': '🎉 Grattis! Du har fått en ny belöning!',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #6366f1;">🎉 Grattis, {{user.first_name}}!</h1>
    
    <p>Du har tjänat in en ny belöning på {{app_name}}!</p>
    
    <div style="background-color: #f3f4f6; border-radius: 12px; padding: 24px; margin: 20px 0; text-align: center;">
        <h2 style="margin: 0; color: #6366f1;">{{reward_name}}</h2>
    </div>
    
    <p>Fortsätt så och samla ännu fler belöningar!</p>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se/rewards" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Visa mina belöningar</a>
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
                'en': {
                    'subject': '🎉 Congratulations! You earned a new reward!',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #6366f1;">🎉 Congratulations, {{user.first_name}}!</h1>
    
    <p>You have earned a new reward on {{app_name}}!</p>
    
    <div style="background-color: #f3f4f6; border-radius: 12px; padding: 24px; margin: 20px 0; text-align: center;">
        <h2 style="margin: 0; color: #6366f1;">{{reward_name}}</h2>
    </div>
    
    <p>Keep going and collect even more rewards!</p>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se/rewards" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">View my rewards</a>
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
            },
        },
        
        # ===== QUESTIONNAIRES =====
        {
            'type': 'new_questionnaire',
            'name': 'New Questionnaire Available',
            'description': 'Sent when a new questionnaire is available for the user',
            'available_variables': [
                {'name': 'user.first_name', 'description': 'User\'s first name'},
                {'name': 'questionnaire_name', 'description': 'Name of the questionnaire'},
                {'name': 'app_name', 'description': 'Application name'},
            ],
            'translations': {
                'sv': {
                    'subject': 'Ny enkät att fylla i: {{questionnaire_name}}',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333;">Hej {{user.first_name}}!</h1>
    
    <p>Det finns en ny enkät för dig att fylla i på {{app_name}}.</p>
    
    <div style="background-color: #f3f4f6; border-radius: 8px; padding: 20px; margin: 20px 0;">
        <h2 style="margin: 0 0 10px 0; color: #6366f1;">{{questionnaire_name}}</h2>
    </div>
    
    <p>Din feedback är viktig för oss!</p>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se/questionnaires" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Svara på enkäten</a>
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
                'en': {
                    'subject': 'New questionnaire to complete: {{questionnaire_name}}',
                    'body_html': '''
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h1 style="color: #333;">Hi {{user.first_name}}!</h1>
    
    <p>There is a new questionnaire for you to complete on {{app_name}}.</p>
    
    <div style="background-color: #f3f4f6; border-radius: 8px; padding: 20px; margin: 20px 0;">
        <h2 style="margin: 0 0 10px 0; color: #6366f1;">{{questionnaire_name}}</h2>
    </div>
    
    <p>Your feedback is important to us!</p>
    
    <div style="margin: 30px 0; text-align: center;">
        <a href="https://ungdomsappen.se/questionnaires" style="background-color: #6366f1; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; display: inline-block;">Answer the questionnaire</a>
    </div>
    
    <hr style="border: none; border-top: 1px solid #eee; margin: 30px 0;">
    
    <p style="color: #999; font-size: 12px;">{{app_name}} | {{support_email}}</p>
</div>
''',
                },
            },
        },
    ]

    # Create templates and their translations
    for template_data in templates:
        template = EmailTemplate.objects.create(
            type=template_data['type'],
            name=template_data['name'],
            description=template_data['description'],
            available_variables=template_data['available_variables'],
            is_active=True,
        )
        
        for lang_code, translation_data in template_data['translations'].items():
            EmailTemplateTranslation.objects.create(
                template=template,
                language=lang_code,
                subject=translation_data['subject'],
                body_html=translation_data['body_html'].strip(),
                body_text='',  # Will be auto-generated when sending
            )


def delete_default_templates(apps, schema_editor):
    """Remove default templates."""
    EmailTemplate = apps.get_model('emails', 'EmailTemplate')
    EmailTemplate.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_templates, delete_default_templates),
    ]
