# Generated by Django 5.2.8 on 2025-12-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_add_default_templates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('deletion_warning_first', 'Deletion Warning (First - 30 days)'), ('deletion_warning_final', 'Deletion Warning (Final - 7 days)'), ('account_deleted', 'Account Deleted Confirmation'), ('new_message', 'New Message Received'), ('new_event', 'New Event Published'), ('event_reminder', 'Event Reminder'), ('event_cancelled', 'Event Cancelled'), ('welcome', 'Welcome Email'), ('guardian_link_request', 'Guardian Link Request'), ('guardian_link_approved', 'Guardian Link Approved'), ('reward_earned', 'Reward Earned'), ('new_questionnaire', 'New Questionnaire Available'), ('two_factor_otp', 'Two-Factor Authentication OTP')], help_text='The type of email this template is for', max_length=50, unique=True),
        ),
    ]
