# Generated by Django 5.2.8 on 2026-01-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_add_new_email_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('deletion_warning_first', 'Deletion Warning (First - 30 days)'), ('deletion_warning_final', 'Deletion Warning (Final - 7 days)'), ('account_deleted', 'Account Deleted Confirmation'), ('new_message', 'New Message Received'), ('new_post', 'New Post Published'), ('new_event', 'New Event Published'), ('event_reminder', 'Event Reminder'), ('event_cancelled', 'Event Cancelled'), ('event_registration_confirmed', 'Event Registration Confirmed'), ('welcome', 'Welcome Email'), ('guardian_created', 'Guardian Account Created'), ('guardian_link_request', 'Guardian Link Request'), ('guardian_link_approved', 'Guardian Link Approved'), ('birthday', 'Birthday Greeting'), ('trial_expiring', 'Trial Period Expiring'), ('reward_earned', 'Reward Earned'), ('new_questionnaire', 'New Questionnaire Available'), ('two_factor_otp', 'Two-Factor Authentication OTP'), ('password_reset', 'Password Reset Request'), ('data_export_ready', 'Data Export Ready'), ('data_export_failed', 'Data Export Failed')], help_text='The type of email this template is for', max_length=60, unique=True),
        ),
    ]
