# Generated by Django 5.2.8 on 2025-12-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_recommended',
            field=models.BooleanField(default=False, help_text='Show in Recommended section by default'),
        ),
        migrations.AddField(
            model_name='course',
            name='related_courses',
            field=models.ManyToManyField(blank=True, help_text='Suggested next courses', to='learning.course'),
        ),
    ]
