# Generated by Django 5.2.8 on 2025-11-28 04:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('organization', '0006_remove_regularopeninghour_allowed_age_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='rewards/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('sponsor_name', models.CharField(blank=True, max_length=200)),
                ('sponsor_link', models.URLField(blank=True, null=True)),
                ('owner_role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MUNICIPALITY_ADMIN', 'Municipality Admin'), ('CLUB_ADMIN', 'Club Admin')], max_length=50)),
                ('target_genders', models.JSONField(blank=True, default=list)),
                ('target_grades', models.JSONField(blank=True, default=list)),
                ('min_age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_age', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('target_member_type', models.CharField(choices=[('YOUTH', 'Youth Only'), ('GUARDIAN', 'Guardians Only')], default='YOUTH', max_length=20)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('usage_limit', models.IntegerField(blank=True, help_text='Total times this reward can be claimed. Null = Unlimited.', null=True)),
                ('active_triggers', models.JSONField(blank=True, default=list, help_text='List of active trigger codes')),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='organization.club')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='organization.municipality')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='targeted_rewards', to='groups.group')),
                ('target_interests', models.ManyToManyField(blank=True, related_name='targeted_rewards', to='organization.interest')),
            ],
        ),
        migrations.CreateModel(
            name='RewardUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='rewards.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
    ]
