# Generated by Django 5.2.8 on 2025-11-28 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='target_member_type',
            field=models.CharField(choices=[('YOUTH_MEMBER', 'Youth Member'), ('GUARDIAN', 'Guardians Only')], default='YOUTH_MEMBER', max_length=20),
        ),
    ]
