# Generated by Django 5.2.8 on 2025-11-28 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_alter_reward_target_member_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardusage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='rewardusage',
            old_name='used_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='rewardusage',
            name='is_redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rewardusage',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
