# Generated by Django 5.2.8 on 2026-01-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_alter_rewardusage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardusage',
            name='trigger_context',
            field=models.JSONField(blank=True, default=dict, help_text='Context data for the trigger (e.g. milestone_reached, event_id, group_id, anniversary_year)'),
        ),
        migrations.AddField(
            model_name='rewardusage',
            name='trigger_type',
            field=models.CharField(blank=True, help_text='The trigger that granted this reward', max_length=50),
        ),
    ]
