# Generated by Django 5.2.8 on 2026-01-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_rewardusage_trigger_context_rewardusage_trigger_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='active_triggers',
            field=models.JSONField(blank=True, default=list, help_text='Single trigger code stored as list for compatibility'),
        ),
    ]
