# Generated by Django 5.2.8 on 2025-12-02 19:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0007_club_allow_self_registration_override_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Material Icon name or Emoji', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Item Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(blank=True, help_text='Material Icon name or Emoji', max_length=50)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_tags', to='organization.club')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'club')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='inventory/items/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('max_borrow_duration', models.IntegerField(default=60, help_text='Maximum borrowing time in minutes. 0 = Until Close.', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('BORROWED', 'Borrowed'), ('MAINTENANCE', 'In Maintenance (Broken)'), ('MISSING', 'Missing / Lost'), ('HIDDEN', 'Hidden (Archived)')], default='AVAILABLE', max_length=20)),
                ('internal_note', models.CharField(blank=True, help_text="Admin note (e.g. 'Batch 2024')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='organization.club')),
                ('tags', models.ManyToManyField(blank=True, related_name='items', to='inventory.inventorytag')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.itemcategory')),
            ],
            options={
                'ordering': ['title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LendingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True)),
                ('due_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETURNED_USER', 'Returned by User'), ('RETURNED_SYSTEM', 'Auto-Returned by System (Closing)'), ('RETURNED_ADMIN', 'Force Returned by Admin')], default='ACTIVE', max_length=20)),
                ('is_guest', models.BooleanField(default=False, help_text='Was the user a guest at this club?')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lending_sessions', to='inventory.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lending_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-borrowed_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('notified_at', models.DateTimeField(blank=True, help_text='When user was told item is free', null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_list', to='inventory.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['queued_at'],
            },
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['club', 'status'], name='inventory_i_club_id_993a3b_idx'),
        ),
        migrations.AddIndex(
            model_name='lendingsession',
            index=models.Index(fields=['user', 'status'], name='inventory_l_user_id_cd32d1_idx'),
        ),
        migrations.AddIndex(
            model_name='lendingsession',
            index=models.Index(fields=['item', 'status'], name='inventory_l_item_id_a30e10_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='waitinglist',
            unique_together={('item', 'user')},
        ),
    ]
