# Generated by Django 5.2.8 on 2026-01-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupmembership_rejection_count'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='restricted_to_group',
            field=models.ForeignKey(blank=True, help_text='If set, only members of this group can see and borrow this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restricted_items', to='groups.group'),
        ),
    ]
