# Generated by Django 5.2.8 on 2026-01-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_add_restricted_to_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='requires_checkin',
            field=models.BooleanField(blank=True, default=None, help_text="Override club's check-in requirement for this item. None = use club default.", null=True),
        ),
    ]
