# Generated by Django 5.2.8 on 2026-01-02 11:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='detected_location',
            field=models.ForeignKey(blank=True, help_text='Auto-detected location from keyword text', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_keywords', to='seo.swedishlocation'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='generated_article',
            field=models.OneToOneField(blank=True, help_text='Article generated from this keyword', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_keyword_link', to='seo.seoarticle'),
        ),
        migrations.AddField(
            model_name='keyword',
            name='generated_page',
            field=models.OneToOneField(blank=True, help_text='Landing page generated from this keyword', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_keyword_link', to='seo.locallandingpage'),
        ),
        migrations.AddField(
            model_name='locallandingpage',
            name='faq_items',
            field=models.JSONField(blank=True, default=list, help_text="FAQ items: [{'question': '...', 'answer': '...'}, ...]"),
        ),
        migrations.AddField(
            model_name='locallandingpage',
            name='focus_keyphrase',
            field=models.CharField(blank=True, help_text='Primary keyword/phrase this page targets (auto-set from keyword)', max_length=100),
        ),
        migrations.AddField(
            model_name='locallandingpage',
            name='reading_time_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes'),
        ),
        migrations.AddField(
            model_name='locallandingpage',
            name='twitter_card',
            field=models.CharField(choices=[('summary', 'Summary'), ('summary_large_image', 'Summary Large Image')], default='summary_large_image', help_text='Twitter card type', max_length=50),
        ),
        migrations.AddField(
            model_name='locallandingpage',
            name='twitter_description',
            field=models.TextField(blank=True, help_text='Twitter description (defaults to og_description)', max_length=200),
        ),
        migrations.AddField(
            model_name='locallandingpage',
            name='twitter_image',
            field=models.ImageField(blank=True, help_text='Twitter image (defaults to og_image)', null=True, upload_to='seo/local-pages/twitter/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='locallandingpage',
            name='twitter_title',
            field=models.CharField(blank=True, help_text='Twitter title (defaults to og_title or title)', max_length=70),
        ),
        migrations.AddField(
            model_name='locallandingpage',
            name='word_count',
            field=models.PositiveIntegerField(default=0, help_text='Total word count of content'),
        ),
    ]
