# Generated by Django 5.2.8 on 2026-01-02 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_keyword_detected_location_keyword_generated_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locallandingpage',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero image for page banner (1200x630 recommended)', null=True, upload_to='seo/local-pages/hero/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='locallandingpage',
            name='hero_image_alt',
            field=models.CharField(blank=True, help_text='Alt text for hero image (important for SEO)', max_length=200),
        ),
    ]
