# Generated by Django 5.2.8 on 2026-01-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_add_hero_image_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoarticle',
            name='content',
            field=models.TextField(blank=True, default='', help_text='Full article content (markdown supported)'),
        ),
        migrations.AlterField(
            model_name='seoarticle',
            name='excerpt',
            field=models.TextField(blank=True, default='', help_text='Short excerpt for previews', max_length=300),
        ),
        migrations.AlterField(
            model_name='seoarticle',
            name='h1_title',
            field=models.CharField(blank=True, default='', help_text='H1 title (can differ from SEO title)', max_length=100),
        ),
        migrations.AlterField(
            model_name='seoarticle',
            name='meta_description',
            field=models.TextField(blank=True, default='', help_text='Meta description (max 160 chars)', max_length=160),
        ),
    ]
