# Generated by Django 5.2.8 on 2025-11-28 12:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('organization', '0006_remove_regularopeninghour_allowed_age_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Rich text content')),
                ('post_type', models.CharField(choices=[('TEXT', 'Text Post'), ('IMAGE', 'Image Post'), ('VIDEO', 'Video Post')], default='TEXT', max_length=20)),
                ('video_url', models.URLField(blank=True, help_text='YouTube link', null=True)),
                ('owner_role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MUNICIPALITY_ADMIN', 'Municipality Admin'), ('CLUB_ADMIN', 'Club Admin')], max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived/Expired')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='When the post goes live', null=True)),
                ('visibility_start_date', models.DateTimeField(blank=True, null=True)),
                ('visibility_end_date', models.DateTimeField(blank=True, help_text='Auto-hide after this date', null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('pinned_until', models.DateTimeField(blank=True, null=True)),
                ('target_member_type', models.CharField(choices=[('YOUTH', 'Youth Only'), ('GUARDIAN', 'Guardians Only'), ('BOTH', 'Both Youth and Guardians')], default='BOTH', max_length=20)),
                ('target_genders', models.JSONField(blank=True, default=list, help_text='List of genders e.g. ["MALE", "FEMALE"]')),
                ('target_grades', models.JSONField(blank=True, default=list, help_text='List of grades e.g. [7, 8, 9]')),
                ('target_min_age', models.IntegerField(blank=True, null=True)),
                ('target_max_age', models.IntegerField(blank=True, null=True)),
                ('target_custom_fields', models.JSONField(blank=True, default=dict)),
                ('allow_comments', models.BooleanField(default=True)),
                ('require_moderation', models.BooleanField(default=False, help_text='If true, comments must be approved')),
                ('limit_comments_per_user', models.IntegerField(default=0, help_text='0 = Unlimited')),
                ('allow_replies', models.BooleanField(default=True)),
                ('send_push_notification', models.BooleanField(default=False)),
                ('push_title', models.CharField(blank=True, max_length=200)),
                ('push_message', models.CharField(blank=True, max_length=200)),
                ('view_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_posts', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='organization.club')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='organization.municipality')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='targeted_posts', to='groups.group')),
                ('target_interests', models.ManyToManyField(blank=True, related_name='targeted_posts', to='organization.interest')),
            ],
            options={
                'ordering': ['-is_pinned', '-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.postcomment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='posts/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('order', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='posts.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
