# Generated by Django 5.2.8 on 2025-11-28 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_remove_regularopeninghour_allowed_age_groups_and_more'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Visible to everyone (Super Admin only)'),
        ),
        migrations.AddField(
            model_name='post',
            name='target_clubs',
            field=models.ManyToManyField(blank=True, related_name='targeted_posts', to='organization.club'),
        ),
        migrations.AddField(
            model_name='post',
            name='target_municipalities',
            field=models.ManyToManyField(blank=True, related_name='targeted_posts', to='organization.municipality'),
        ),
        migrations.AlterField(
            model_name='post',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_posts', to='organization.club'),
        ),
        migrations.AlterField(
            model_name='post',
            name='municipality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_posts', to='organization.municipality'),
        ),
    ]
