# Generated by Django 5.2.8 on 2025-11-29 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postreaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='postreaction',
            name='reaction_type',
            field=models.CharField(choices=[('LIKE', 'Like'), ('LOVE', 'Love'), ('LAUGH', 'Laugh'), ('WOW', 'Wow'), ('SAD', 'Sad'), ('ANGRY', 'Angry')], default='LIKE', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='postreaction',
            unique_together={('post', 'user', 'reaction_type')},
        ),
    ]
