# Generated by Django 5.2.8 on 2025-12-22 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_groupmembership_rejection_count'),
        ('organization', '0008_club_borrowing_requires_checkin_and_more'),
        ('posts', '0004_alter_postreaction_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, help_text='Brief summary of what this template is for')),
                ('icon', models.CharField(choices=[('MEGAPHONE', '📢 Announcement'), ('CALENDAR', '📅 Event'), ('STAR', '⭐ Featured'), ('BELL', '🔔 Reminder'), ('PARTY', '🎉 Celebration'), ('INFO', 'ℹ️ Information'), ('WARNING', '⚠️ Important'), ('HEART', '❤️ Community'), ('TROPHY', '🏆 Achievement'), ('ROCKET', '🚀 Update')], default='MEGAPHONE', max_length=20)),
                ('role_scope', models.CharField(choices=[('SUPER', 'Super Admin'), ('MUNICIPALITY', 'Municipality Admin'), ('CLUB', 'Club Admin')], max_length=20)),
                ('is_global', models.BooleanField(default=False, help_text='Visible to everyone (Super Admin only)')),
                ('default_post_type', models.CharField(choices=[('TEXT', 'Text Post'), ('IMAGE', 'Image Post'), ('VIDEO', 'Video Post')], default='TEXT', max_length=20)),
                ('target_member_type', models.CharField(choices=[('YOUTH', 'Youth Only'), ('GUARDIAN', 'Guardians Only'), ('BOTH', 'Both Youth and Guardians')], default='BOTH', max_length=20)),
                ('target_min_age', models.IntegerField(blank=True, null=True)),
                ('target_max_age', models.IntegerField(blank=True, null=True)),
                ('target_grades', models.JSONField(blank=True, default=list)),
                ('target_genders', models.JSONField(blank=True, default=list)),
                ('target_custom_fields', models.JSONField(blank=True, default=dict)),
                ('allow_comments', models.BooleanField(default=True)),
                ('require_moderation', models.BooleanField(default=False)),
                ('allow_replies', models.BooleanField(default=True)),
                ('limit_comments_per_user', models.IntegerField(default=0)),
                ('send_push_notification', models.BooleanField(default=False)),
                ('default_push_title', models.CharField(blank=True, max_length=200)),
                ('is_pinned_default', models.BooleanField(default=False)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of posts created using this template')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive templates are hidden from selection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_templates', to='organization.club')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_templates', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_templates', to='organization.municipality')),
                ('target_clubs', models.ManyToManyField(blank=True, related_name='template_targets', to='organization.club')),
                ('target_groups', models.ManyToManyField(blank=True, related_name='post_templates', to='groups.group')),
                ('target_interests', models.ManyToManyField(blank=True, related_name='post_templates', to='organization.interest')),
                ('target_municipalities', models.ManyToManyField(blank=True, related_name='template_targets', to='organization.municipality')),
            ],
            options={
                'ordering': ['-usage_count', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='created_from_template',
            field=models.ForeignKey(blank=True, help_text='The template used to create this post (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts_created', to='posts.posttemplate'),
        ),
    ]
