# Generated by Django 5.2.8 on 2025-12-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_posttemplate_post_created_from_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttemplate',
            name='default_push_message',
            field=models.CharField(blank=True, help_text='Default push notification body text', max_length=500),
        ),
    ]
