# Generated by Django 5.2.8 on 2025-11-26 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0006_remove_regularopeninghour_allowed_age_groups_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label for the field', max_length=255)),
                ('help_text', models.CharField(blank=True, help_text='Hint text displayed to user', max_length=255, null=True)),
                ('field_type', models.CharField(choices=[('TEXT', 'Text Field'), ('SINGLE_SELECT', 'Single Select'), ('MULTI_SELECT', 'Multi Select'), ('BOOLEAN', 'Boolean (Checkbox)')], default='TEXT', max_length=20)),
                ('options', models.JSONField(blank=True, default=list, help_text='List of options for select fields')),
                ('required', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('context', models.CharField(choices=[('USER_PROFILE', 'User Profile'), ('EVENT', 'Event')], default='USER_PROFILE', max_length=20)),
                ('target_roles', models.JSONField(default=list)),
                ('owner_role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('MUNICIPALITY_ADMIN', 'Municipality Admin'), ('CLUB_ADMIN', 'Club Admin')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='organization.club')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='organization.municipality')),
                ('specific_clubs', models.ManyToManyField(blank=True, help_text='If set, only applies to these clubs within the municipality', related_name='specific_custom_fields', to='organization.club')),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='custom_fields.customfielddefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('field', 'user')},
            },
        ),
    ]
