# Generated by Django 5.2.8 on 2025-12-27 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields', '0001_initial'),
        ('events', '0007_fix_target_max_age_validator'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_custom_fields', to='events.event')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_usages', to='custom_fields.customfielddefinition')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('event', 'field')},
            },
        ),
        migrations.CreateModel(
            name='EventRegistrationCustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registration_values', to='custom_fields.customfielddefinition')),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_field_values', to='events.eventregistration')),
            ],
            options={
                'unique_together': {('registration', 'field')},
            },
        ),
    ]
