# Generated by Django 5.2.8 on 2025-11-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_interest'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.IntegerField(blank=True, help_text='Current school grade (e.g. 7, 8, 9). Updates automatically on July 1st.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, help_text='Interests selected by the youth member', related_name='users', to='organization.interest'),
        ),
    ]
