# Generated by Django 5.2.8 on 2025-11-23 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_interest_avatar'),
        ('users', '0002_user_grade_user_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_club',
            field=models.ForeignKey(blank=True, help_text='For Club Admins', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='organization.club'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_municipality',
            field=models.ForeignKey(blank=True, help_text='For Municipality Admins', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admins', to='organization.municipality'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_club',
            field=models.ForeignKey(blank=True, help_text='Primary club for the youth member', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='organization.club'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.IntegerField(blank=True, help_text='Current school grade. Updates automatically on July 1st.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='users', to='organization.interest'),
        ),
        migrations.CreateModel(
            name='GuardianYouthLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('MOTHER', 'Mother'), ('FATHER', 'Father'), ('GUARDIAN', 'Legal Guardian'), ('SIBLING', 'Sibling'), ('OTHER', 'Other')], max_length=20)),
                ('is_primary_guardian', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youth_links', to=settings.AUTH_USER_MODEL)),
                ('youth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('guardian', 'youth')},
            },
        ),
    ]
