# Generated by Django 5.2.8 on 2025-11-23 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_assigned_club_user_assigned_municipality_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Club Staff',
                'verbose_name_plural': 'Club Staff',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
            ],
            options={
                'verbose_name': 'Guardian',
                'verbose_name_plural': 'Guardians',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='MunicipalityAdmin',
            fields=[
            ],
            options={
                'verbose_name': 'Municipality Admin',
                'verbose_name_plural': 'Municipality Admins',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.CreateModel(
            name='YouthMember',
            fields=[
            ],
            options={
                'verbose_name': 'Youth Member',
                'verbose_name_plural': 'Youth Members',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hide_contact_info',
            field=models.BooleanField(default=False, help_text='Hide contact info from Youth/Guardians'),
        ),
        migrations.AddField(
            model_name='user',
            name='legal_gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], help_text='Legal/Biological gender', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, help_text='Display name or Nickname', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_gender',
            field=models.CharField(blank=True, help_text='Self-identified gender (if different from legal)', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, help_text='Job title or Profession', max_length=100),
        ),
        migrations.AlterField(
            model_name='guardianyouthlink',
            name='guardian',
            field=models.ForeignKey(limit_choices_to={'role': 'GUARDIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='youth_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guardianyouthlink',
            name='youth',
            field=models.ForeignKey(limit_choices_to={'role': 'YOUTH_MEMBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
