# Generated by Django 5.2.8 on 2025-11-23 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_clubadmin_guardian_municipalityadmin_youthmember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, help_text='User profile picture (jpg, jpeg, png, svg, gif)', null=True, upload_to='users/avatars/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'gif'])]),
        ),
    ]
