# Generated by Django 5.2.8 on 2025-11-30 04:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userloginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_image',
            field=models.FileField(blank=True, help_text='Profile header background image', null=True, upload_to='users/backgrounds/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='mood_status',
            field=models.CharField(blank=True, help_text="Short status message, e.g. 'Playing FIFA' or 'Studying'", max_length=100),
        ),
    ]
