# Generated by Django 5.2.8 on 2025-11-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_club_allow_self_registration_override_and_more'),
        ('users', '0008_user_background_image_user_mood_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_clubs',
            field=models.ManyToManyField(blank=True, help_text='Clubs the youth follows in addition to their preferred club.', related_name='followers', to='organization.club'),
        ),
    ]
