# Generated by Django 5.2.8 on 2025-12-27 08:31

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_followed_clubs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_document',
            field=models.FileField(blank=True, help_text="Scanned ID document (passport, ID card, driver's license)", null=True, upload_to='users/id_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])]),
        ),
        migrations.AddField(
            model_name='user',
            name='id_document_rejection_reason',
            field=models.TextField(blank=True, help_text='Reason for rejecting the ID document (if rejected)'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_document_review_status',
            field=models.CharField(choices=[('NOT_SUBMITTED', 'Not Submitted'), ('PENDING_REVIEW', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NOT_SUBMITTED', help_text='Review status of the uploaded ID document', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='id_document_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When the ID document was reviewed', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='id_document_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed the ID document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='id_document_type',
            field=models.CharField(blank=True, choices=[('PASSPORT', 'Passport'), ('ID_CARD', 'ID Card'), ('DRIVERS_LICENSE', "Driver's License"), ('OTHER', 'Other')], help_text='Type of ID document uploaded', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='id_document_uploaded_at',
            field=models.DateTimeField(blank=True, help_text='When the ID document was uploaded', null=True),
        ),
    ]
