# Generated by Django 5.2.8 on 2025-12-27 08:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_id_document_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdDocumentUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(help_text='Scanned ID document', upload_to='users/id_documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf'])])),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('ID_CARD', 'ID Card'), ('DRIVERS_LICENSE', "Driver's License"), ('OTHER', 'Other')], help_text='Type of ID document', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DELETED', 'Deleted by Admin')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if rejected)')),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admins')),
                ('guardian', models.ForeignKey(limit_choices_to={'role': 'GUARDIAN'}, on_delete=django.db.models.deletion.CASCADE, related_name='id_document_uploads', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_id_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
