# Generated by Django 5.2.8 on 2025-12-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_id_document_upload_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_final_warning_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the final deletion warning was sent', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_warning_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the first deletion warning was sent', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active_at',
            field=models.DateTimeField(blank=True, help_text='Last meaningful activity (login, check-in, etc.). Used for data retention.', null=True),
        ),
    ]
