# Generated by Django 5.2.8 on 2025-12-28 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_user_deletion_final_warning_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(help_text='SHA-256 hash of the OTP code', max_length=64, verbose_name='Code Hash')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('purpose', models.CharField(default='login', help_text='Why this OTP was generated', max_length=50, verbose_name='Purpose')),
                ('requested_from_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Requested From IP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'OTP Code',
                'verbose_name_plural': 'OTP Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA-256 hash of the device trust token', max_length=64, unique=True, verbose_name='Token Hash')),
                ('device_name', models.CharField(blank=True, help_text='User agent or friendly device name', max_length=200, verbose_name='Device Name')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when device was trusted', null=True, verbose_name='IP Address')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='Last Used At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Trusted Device',
                'verbose_name_plural': 'Trusted Devices',
                'ordering': ['-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTwoFactorSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text="For Guardians: whether they've opted into 2FA", verbose_name='2FA Enabled')),
                ('first_2fa_completed_at', models.DateTimeField(blank=True, help_text='When the user first completed 2FA verification', null=True, verbose_name='First 2FA Completed')),
                ('last_verified_at', models.DateTimeField(blank=True, help_text='When the user last successfully verified 2FA', null=True, verbose_name='Last 2FA Verification')),
                ('failed_attempts', models.PositiveIntegerField(default=0, help_text='Number of consecutive failed OTP attempts', verbose_name='Failed Attempts')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Account 2FA is locked until this time due to too many failed attempts', null=True, verbose_name='Locked Until')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='two_factor_settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User 2FA Settings',
                'verbose_name_plural': 'User 2FA Settings',
            },
        ),
    ]
