# Generated by Django 5.2.8 on 2026-01-01 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_two_factor_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trial_started_at',
            field=models.DateTimeField(blank=True, help_text="When the user's trial period started (set on first login for unverified youth)", null=True),
        ),
    ]
