# Generated by Django 5.2.8 on 2026-01-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_trial_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertwofactorsettings',
            name='bypass_until',
            field=models.DateTimeField(blank=True, help_text='Admin-set bypass to skip 2FA until this date', null=True, verbose_name='Bypass Until'),
        ),
    ]
