# Generated by Django 5.2.8 on 2026-01-12 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField(help_text='Original AuditLog ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254)),
                ('admin_user_id', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Archived Audit Log',
                'verbose_name_plural': 'Archived Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', '-timestamp'], name='audit_arch_user_time_idx'), models.Index(fields=['-timestamp'], name='audit_arch_time_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('READ', 'Accessed'), ('UPDATE', 'Modified'), ('DELETE', 'Deleted'), ('EXPORT', 'Exported'), ('LOGIN', 'Logged in'), ('LOGOUT', 'Logged out'), ('LOGIN_FAILED', 'Login failed'), ('PASSWORD_RESET', 'Password reset'), ('PASSWORD_CHANGE', 'Password changed'), ('CONSENT_GIVEN', 'Consent given'), ('CONSENT_WITHDRAWN', 'Consent withdrawn'), ('DATA_EXPORT_REQUESTED', 'Data export requested'), ('DELETION_REQUESTED', 'Account deletion requested'), ('DELETION_CANCELLED', 'Deletion cancelled'), ('ADMIN_VIEW', 'Admin viewed data'), ('ADMIN_UPDATE', 'Admin modified data'), ('ADMIN_DELETE', 'Admin deleted data')], db_index=True, help_text='Type of action performed', max_length=50)),
                ('model_name', models.CharField(db_index=True, help_text='Model/table name affected', max_length=100)),
                ('object_id', models.IntegerField(blank=True, db_index=True, help_text='ID of the object affected', null=True)),
                ('object_repr', models.CharField(blank=True, help_text='String representation of the object', max_length=200)),
                ('changes', models.JSONField(blank=True, help_text='Before/after values for updates', null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the action (optional)')),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, help_text='IP address of the request', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent')),
                ('endpoint', models.CharField(blank=True, db_index=True, help_text='API endpoint accessed', max_length=200)),
                ('method', models.CharField(blank=True, help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('admin_user', models.ForeignKey(blank=True, help_text='Admin who performed action on behalf of or affecting another user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_user_time_idx'), models.Index(fields=['model_name', 'object_id'], name='audit_object_idx'), models.Index(fields=['action', '-timestamp'], name='audit_action_time_idx'), models.Index(fields=['-timestamp'], name='audit_timestamp_idx'), models.Index(fields=['ip_address', '-timestamp'], name='audit_ip_time_idx')],
            },
        ),
    ]
