# Generated by Django 5.2.8 on 2025-11-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('INFO', 'Information'), ('IMPORTANT', 'Important'), ('WARNING', 'Warning')], default='INFO', max_length=20)),
                ('target_roles', models.JSONField(default=list, help_text='List of roles or ["ALL"]')),
                ('is_sticky', models.BooleanField(default=False, help_text='If true, reappears on refresh even if closed')),
                ('external_link', models.URLField(blank=True, help_text='Optional link to read more', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
